### ISSUE TITLE
please where is the link to the best guide on how ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6665] opened 2018-10-09 07:57 UTC
*Help Desk query collected when no chat operators were online. Follow up required.*

please where is the link to the best guide on how to use wormbase effectively and efficiently? thanks. i am waiting and its urgent

**Reported by:** solo*** (aszy***********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/about/userguide/for_users">https://wormbase.org/about/userguide/for_users</a>
**Browser:** Firefox 62.0

**Comment by chris-grove** [comment] 2018-10-10 13:59
Duplicate of #6666

**Closed by chris-grove** 2018-10-10 13:59 UTC
Labels: HelpDesk, source: offline chat
