### ISSUE TITLE
  Coding_transcript: An automatically g...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6392] opened 2018-05-03 09:00 UTC
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Coding_transcript: An automatically generated transcript object produced by building UTRs onto the curated CDS structure utilising sequence data from a variety of sources. </p><p>What were you doing? <br />&nbsp;&nbsp;I do not understand the meaning of "Coding_transcript" . And i also want to know what is " the curated CDS structure "</p>

**Reported by:** 1731***************
**Submitted from:** <a target="_blank" href="https://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36 Edge/16.16299

**Comment by Paul-Davis** [comment] 2018-05-03 10:18
duplicate of #6394

**Closed by Paul-Davis** 2018-05-03 10:18 UTC
Labels: HelpDesk
