### ISSUE TITLE
 Server Error: 500 at  rest/widget/paper/WBPaper00...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3926] opened 2015-06-04 15:28 UTC
<p>Server Error: 500 at <a href="http://www.wormbase.org/rest/widget/paper/WBPaper00046339/overview">rest/widget/paper/WBPaper00046339/overview</a></p><p></p><p>Error Message:<br> Caught exception in WormBase::Web::Controller::REST->widget "Could not fetch object WBPaper00046339, paper at /var/lib/jenkins/jobs/staging_build/workspace/lib/WormBase/Web/Controller/REST.pm line 671." </p><p>What were you doing? <br />&nbsp;&nbsp;Looking at new reference under pig-1 gene</p>

Reported by: Dian******** (dgm7************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.81 Safari/537.36

**Comment by xdwang** [comment] 2015-06-05 12:53
There is no user's email that I can response to. The issue is fixed in WS248.

**Closed by xdwang** 2015-06-05 12:53 UTC
Labels: Bug Report, HelpDesk

**Comment by xdwang** [comment] 2015-06-05 17:03
respond at email address: dgm7@cornell.edu
Hi Diane,

Thanks for reporting to wormbase. We already realized the issue and fix the problem for sooner new release wormbase WS248.

At same time, you can refer to this page for the reference you are  interested in:

http://staging.wormbase.org/resources/paper/WBPaper00046339#0--10


Best,

Xiaodong Wang
wormbase help desk officer
