### ISSUE TITLE
  I tried to use WormMine to find all g...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5033] opened 2016-08-17 14:13 UTC
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I tried to use WormMine to find all genes within a genomic interval. However, I get a "no results" output.<br/>Can you please guide me (it used to be so much easier with the previous wormbase version.<br/>Thank you,<br/>Einav.</p>

**Reported by:** Eina******* (eina******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36

**Comment by chris-grove** [comment] 2016-08-17 14:25
Hi Einav,


 Apologies, WormMine is having trouble with querying gene location right now. You can, however, query transcript location. The following query XML:


`<query name="" model="genomic" view="Gene.primaryIdentifier Gene.secondaryIdentifier Gene.symbol Gene.organism.name Gene.transcripts.chromosome.primaryIdentifier Gene.transcripts.chromosomeLocation.start Gene.transcripts.chromosomeLocation.end Gene.transcripts.chromosomeLocation.strand" longDescription="Returns all genes within a specified chromosomal interval in a given species" sortOrder="Gene.primaryIdentifier asc" constraintLogic="D and A and B and C">
  <constraint path="Gene.organism.name" code="D" op="=" value="Caenorhabditis elegans"/>
  <constraint path="Gene.transcripts.chromosome.primaryIdentifier" code="A" op="=" value="X"/>
  <constraint path="Gene.transcripts.chromosomeLocation.start" code="B" op="&gt;=" value="1000000"/>
  <constraint path="Gene.transcripts.chromosomeLocation.end" code="C" op="&lt;=" value="1500000"/>
</query>`


can be imported via the "Import query from XML" option on the QueryBuilder tab of WormMine. Paste in the XML and click "Submit" and you should be directed to a QueryBuilder page for the query. You can click on the blue edit icons net to chromosome WormBase ID (currently set to "X") or the Start and End Chromosome locations (currently set to >= 1,000,000 and <= 1,500,000, respectively) to customize your query settings.


Note that there may be multiple results per gene, when more than one transcript is present within the specified interval.


I hope that helps.


Best,


Chris Grove

WormBase

**Comment by chris-grove** [comment] 2016-08-17 14:27
@nuin @tharris 
Can we remove the template query "Chromosome Interval --> Genes" and replace it with a working transcript-based query? Or edit the query to work of transcript location instead of gene location, which isn't working right now?

**Comment by chris-grove** [comment] 2016-08-17 15:06
This is a duplicate of #5004  Closing

**Closed by chris-grove** 2016-08-17 15:06 UTC
Labels: HelpDesk, Intermine
