### ISSUE TITLE
Tree Display

### ISSUE THREAD

**Issue by tuli** [WormBase/website#5374] opened 2017-01-20 10:09 UTC
The Tree Display on the Production site has been down for quite a while. OK on Staging.

**Comment by sibyl229** [comment] 2017-01-20 16:16
Hi @tuli Todd probably has started ACeDB, and it looks like tree display is working now: http://www.wormbase.org/species/c_elegans/gene/WBGene00015146#h-g-3 Feel free to let us know if it's down again. Thanks!

**Comment by tuli** [comment] 2017-01-26 14:54
Tree display giving a gateway time out error.http://www.wormbase.org/species/c_elegans/variation/WBVar02144131#0-54362719-10

**Comment by tuli** [comment] 2017-02-21 11:41
http://www.wormbase.org/resources/paper/WBPaper00031462#05--10 Tree display timing out.

**Comment by tuli** [comment] 2017-04-20 10:03
http://www.wormbase.org/resources/molecule/WBMol:00001845#01237--10 Tree display timing out

**Comment by epaule** [comment] 2017-04-21 15:33
duplicate of #5436

**Closed by epaule** 2017-04-21 15:33 UTC
Labels: UI-app behavior, Webteam
