### ISSUE TITLE
 Server Error: 500 at  tools/blast_blat/run   
  E...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4469] opened 2016-01-07 20:04 UTC
*Submitted from the feedback form on the WormBase website.*

<p>Server Error: 500 at <a href="http://www.wormbase.org/tools/blast_blat/run">tools/blast_blat/run</a></p><p>
</p><p>Error Message:<br> Caught exception in WormBase::Web::Controller::Tools-&gt;tools "read_file '/usr/local/wormbase/tmp/blast_blat/out_sQICb.out.err' - sysopen: No such file or directory at /var/lib/jenkins/jobs/staging_build/workspace/lib/WormBase/API/Service/blast_blat.pm line 312." </p>

**Reported by:** adam********************
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/blast_blat/run">/tools/blast_blat/run</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36

**Comment by chris-grove** [comment] 2016-01-07 20:23
May be duplicate of #4468

**Comment by chris-grove** [comment] 2016-01-07 20:28
Hello Adam,

 Apologies for the error and thank you for reporting the problem.

There seems to be a sporadic bug affecting BLAST that our web team is
currently working on. I am able to get the BLAST to work by retrying the
query. Hopefully that will work for you until we can fix the problem
completely.

Best,

Chris Grove
WormBase

**Comment by chris-grove** [comment] 2016-01-07 21:53
Hi Adam, this problem should now be fixed. Please let us know if you have
any more problems. Thanks again!

Chris

**Closed by chris-grove** 2016-01-07 21:53 UTC
Labels: Bug Report, HelpDesk
