### ISSUE TITLE
 Server Error: 500 at  rest/widget/phenotype/WBPhe...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4348] opened 2015-11-08 10:39 UTC
*Submitted from the feedback form on the WormBase website.*

<p>Server Error: 500 at <a href="http://www.wormbase.org/rest/widget/phenotype/WBPhenotype:0000583/go_term">rest/widget/phenotype/WBPhenotype:0000583/go_term</a><p><p>Error Message:<br> Caught exception in WormBase::Web::Controller::REST->widget "Invalid object tag "Term" at /var/lib/jenkins/jobs/staging_build/workspace/lib/WormBase/API/Object/Phenotype.pm line 128." </p><p>What were you doing? <br />&nbsp;&nbsp;Investigating the genes associated with the dumpy and uncoordinated phenotypes.</p>

**Reported by:** Kare* (kazr*****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; InfoPath.3; GWX:QUALIFIED; rv:11.0) like Gecko

**Comment by chris-grove** [comment] 2015-11-09 19:19
Hello Karen,

 Thanks for the bug report and apologies for the inconvenience. Our web team is looking into the issue, which you can follow here:

https://github.com/WormBase/website/issues/4348

Best,

Chris Grove
WormBase

**Comment by chris-grove** [comment] 2015-11-09 19:20
Confirmed on live site and staging:

![screen shot 2015-11-09 at 11 20 00 am](https://cloud.githubusercontent.com/assets/611382/11043916/ddbb0426-86d3-11e5-965f-f52478d6beac.png)

**Comment by vanaukenk** [comment] 2015-11-09 19:30
Hi,
This looks like it might be stemming from the removal of the Term tag in the GO_term model for WS250; the Name tag now houses the GO_term namespace.
--Kimberly

**Comment by sibyl229** [comment] 2016-02-16 18:26
Hi @chris-grove the broken gene ontology widget on Phenotype page is fixed on production http://www.wormbase.org/species/all/phenotype/WBPhenotype:0000583#02--10. I forgot to ask you to close this one.

**Comment by chris-grove** [comment] 2016-02-16 19:22
@sibyl229  OK, looks good, thanks.

**Closed by chris-grove** 2016-02-16 19:22 UTC
Labels: Bug Report, HelpDesk, Helped, Under testing, Webteam
