### ISSUE TITLE
  Hi there! The "Download Track data" f...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3555] opened 2015-01-16 14:04 UTC
<p>&nbsp;&nbsp;Hi there!<br/>The "Download Track data" feature allowing to  Download track data incl. sequence info inside a gff3 file from inside the genome browser results in empty files (of zero  bytes). This was not the case in the previous worm base release.  Regards,<br/>Mark Seifert</p>

Reported by: mark******** (mark***********************)  (obscured for privacy))
Submitted From: Tools <a href="http://www.wormbase.org//header">/header</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/600.2.5 (KHTML, like Gecko) Version/8.0.2 Safari/600.2.5

**Comment by sibyl229** [comment] 2015-01-16 17:04
Hi Mark,

Thanks for reporting this. Our genome browser expert is looking into it, and will contact you ASAP when it’s fixed. Sorry about the problems!

Sibyl

**Comment by scottcain** [comment] 2015-03-03 00:04
I wonder if this was for C. japonica, as the 246 mysql database was having problems.  It seems to be working now.

**Comment by raymond91125** [comment] 2015-03-04 18:15
@scottcain i see two ways to download track data in genome browser:
1. click on the floppy ico at the track of interest (working)
2. in the yellow Search box, right hand, pull down from Annotate Restriciton Sites (empty output still)

**Comment by scottcain** [comment] 2015-03-04 23:00
Oh, I didn't realize that download track data plugin is activated.  I'm not sure it should be because I'm not sure if it's still supported.  Executing it results in a stack trace from BioPerl.  I'll try to figure out if it can be fixed.

**Comment by scottcain** [comment] 2015-03-05 22:14
So the problem is fairly deep in BioPerl (in the mysql adaptor for Bio::DB::SeqFeature::Store); I imagine it is possible for me to fix it, but it will take a considerable amount of time (I'm not at all familiar with the code base, so there would be some "acclimation" time).  Since the SequenceDumper plugin can also dump GFF, perhaps we can consider turning the TrackDumper off. @tharris any thoughts on that?

**Comment by tharris** [comment] 2015-03-05 22:32
Let's disable the TrackDumper.pm plugin.

**Comment by wm75** [comment] 2015-03-06 08:07
As a long-time user of the TrackDumper plugin, let me just point out that the two ways of getting track data are not exactly the same. The SequenceDumper plugin is track-specific and quite often this is not really what I'm looking for. If you have configured gbrowse to show you all kinds of information from different tracks, then it is MUCH more convenient to be able to download all this information ACROSS tracks as a single file using the TrackDumper.
-> I would really like to see the TrackDumper being brought back to a functional state and maintained.

**Comment by scottcain** [comment] 2015-03-06 17:40
Hi Wolfgang (@wm75),

I think you might not be aware of the SequenceDumper plugin, since it isn't currently available in the WormBase GBrowse instance; I think it is a reasonable replacement for the TrackDumper.  It is accessed in the same way, via the plugin menu (the one that usually says "Annotate restriction sites" if you haven't used it for anything).  Please take a look at it in action in this GBrowse instance:

http://dev.wormbase.org:10004/tools/genome/gbrowse/c_elegans_test/?start=9060076;stop=9071680;ref=III;width=800;version=100;flip=0;grid=on;id=4b13ce56bef2c25b6ae36c4db5bd9d1b;l=VARIATIONS_CHANGE_OF_FUNCTION_ALLELES%1EBINDING_SITES_PREDICTED%1EGENES%1ELOCI%3Aoverview

This is my sandbox GBrowse; it doesn't have many tracks enabled but I think it will give you the idea.  Please select "Download Sequence File" from the plugin menu, press the configure button to select GFF3 from the the Sequence File Format menu, and then click Go.  It should provide a GFF file that encompasses all of the tracks visible.  Do you think this would be acceptable?

**Comment by wm75** [comment] 2015-03-06 23:02
ok, I am a bit confused now about the name's of the different tools in GBrowse.
The TrackDumper plugin is the thing you're accessing through the plugin menu as "Download Track Data", right ? I thought the SequenceDumper is what you access by clicking on the disk icons associated with individual tracks, but apparently that's not true ?

That aside:

I remember the "Download Sequence File" option from some years back before it got removed from the Wormbase GBrowse. In fact, I used to use it instead of the TrackDumper until it got removed.
Reactivating it would be perfectly acceptable if it were working correctly!

When I use it in your sandbox, however, the downloaded GFF3 does not have the sequence included, which is somewhat inconvenient. With Genbank format, which would also work for me, the coordinates seem to be all shifted compared to what I'm seeing in the browser so this does not seem to be usable right now.

If these issues (or at least one of them) could be fixed, then "Download Sequence File" could replace "Download Track Data" for my purposes.

By the way, why is "Download Track Data" working just fine from your sandbox ?

Thanks,
Wolfgang

**Comment by scottcain** [comment] 2015-03-08 22:09
Huh, well, isn't that embarrassing?  I seemed to have fixed it "accidentally" while trying to debug it. Yes, I realize goal of debugging is to fix things, but I didn't realize I fixed it: when I was testing the database was a little slow, so I thought I was still getting greeted with the same blank page.

What I don't know yet is whether this is a "robust" fix, or if it will break in other contexts.  I'll try to stress test it on Monday to see if this can be committed back to the GBrowse code base.

**Comment by scottcain** [comment] 2015-03-09 16:54
So I believe I've found the "real" reason the TrackDumper stopped working; it is due to GFF lines like this one for III:

III     Link    assembly_component   1    13783801     .    +    .    Name=III

That "Name=III" means that when the TrackDumper plugin asks for the feature whose name is III it gets two results rather than just the chromosome it's expecting, so instead of returning a scalar it returns a list.  My "accidental fix" I referred to above just added parenthesis so it would only get the first element in the list.  Luckily in this case, it works out fine, since they are the same segment, but since Name attributes don't have to be unique, I can't count on that always working.  So, I won't commit that back to the GBrowse codebase.  

I can however add this fix to WormBase's GBrowse, though if there is an update to GBrowse it will break the TrackDumper again assuming WormBase's data is the same.  One alternative to this is to change the name of the assembly_component features that correspond to whole chromosomes.

**Comment by khowe** [comment] 2015-03-09 17:08
Interesting. In the GFF3 produced by Hinxton, those lines look like this:

gen1a[klh]6: zcat ~ftp/pub/consortia/wormbase/releases/WS247/species/c_elegans/PRJNA13758/c_elegans.PRJNA13758.WS247.annotations.gff3.gz  | grep 'assembly_component' | grep Link
I	Link	assembly_component	1	15072434	.	+	.	Name=CHROMOSOME_I
II	Link	assembly_component	1	15279421	.	+	.	Name=CHROMOSOME_II
III	Link	assembly_component	1	13783801	.	+	.	Name=CHROMOSOME_III
IV	Link	assembly_component	1	17493829	.	+	.	Name=CHROMOSOME_IV
MtDNA	Link	assembly_component	1	13794	.	+	.	Name=CHROMOSOME_MtDNA
V	Link	assembly_component	1	20924180	.	+	.	Name=CHROMOSOME_V
X	Link	assembly_component	1	17718942	.	+	.	Name=CHROMOSOME_X

So it looks like this is another case attributes being changed by the OICR staging code. 

The presence of the CHROMOSOME_ prefixes in the Names above is more by luck than judgement. The prefixes are universally present in all of our local databases, and in "raw" GFF3 produced by Acedb. We strip them out in a post-processing step. It seems that these assembly_component Names fell through the cracks, but perhaps advantageously so here. 

The assumed fix then would be to simply change the OICR GFF pre-processor to leave those names alone. But I'm guessing that that change was put into the pre-processor for a reason. @tharris ?

**Comment by tharris** [comment] 2015-03-09 17:30
Yes, that is exactly the case, @khowe. 

We formerly stripped ALL CHROMOSOME_ occurrences — there were other GBrowse features that broke if IDs in the 9th column still referred to CHROMOSOME_ entries. Basically, broken lookups.

See #3672 for a related proposal.

**Closed** 2015-03-10 17:50 UTC
Labels: !!! Resolve Now (this release), bug, gbrowse, Helped
