### ISSUE TITLE
Please do not display Curator in the Evidence disp...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3481] opened 2014-12-18 17:47 UTC
Please do not display Curator in the Evidence display, this information does not add to the information on the page; however, it can be accessed by anyone who wants to see it through the tree display.  

Reported by: Kare****** (kare**************)  (obscured for privacy)
Submitted From: y250%20(variation) (/species/c_elegans/variation/WBVar00275339#026-45-3-0245)

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36

**Comment by tharris** [comment] 2015-04-24 08:24
If we REALLY want to make curator_confirmed evidence only available to curators, we can do so using member roles in the view. Can curators decide whether they want this displayed or not?

I personally DO think it has value because it is another opportunity for transparency of the value that WormBase is adding.

**Comment by tuli** [comment] 2015-04-24 12:53
I think the issue is that curators use the tag in different ways.

I tend to only add it to my curation if I have added something not in a publication or from a user e.g. explaining why I have curated a molecular lesion in a particular way. e.g. http://www.wormbase.org/species/c_elegans/variation/WBVar00000537 (see Remarks) 

I use it in such a way as to (IMO) be of additional use to our users, not as a tracking tool for WB curators (that's what timestamps are for). 

I will NOT add it just to confirm that I've read a paper for example. e.g. http://www.wormbase.org/species/c_elegans/variation/WBVar00000019 (see Phenotype)

I know not everyone agrees with this and that's fine - nothing's breaking - but I am not sure whether we will be able to reach a consensus.

**Comment by raymond91125** [comment] 2015-04-24 15:41
It seems to me that this problem is most sensibly resolved upstream of the web display level. For those curators who do not want the evidence shown, the evidence should not find its way into WS ACeDB. I would think this is also the easiest solution to implement, considering the difference needs and practices of curators and for different data types.

**Comment by kyook** [comment] 2015-04-24 16:48
I agree with Raymond and Mary Ann, this is a consistency in curatorial tag
use problem.  I will work with someone to fix the data model.

We can close this ticket.

Karen

On Fri, Apr 24, 2015 at 8:41 AM, Raymond Lee <notifications@github.com>
wrote:

> It seems to me that this problem is most sensibly resolved upstream of the
> web display level. For those curators who do not want the evidence shown,
> the evidence should not find its way into WS ACeDB. I would think this is
> also the easiest solution to implement, considering the difference needs
> and practices of curators and for different data types.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WormBase/website/issues/3481#issuecomment-95970576>.
>



-- 
~~~~
Karen Yook

Curator
WormBase Caltech
Tel: 626.395.5878
e-mail: kyook@caltech.edu
e-mail: kyook@wormbase.org
skype name: wbkaren

**Closed** 2015-04-27 18:03 UTC
Labels: feature request
