### ISSUE TITLE
 Server Error: 500 at  rest/widget/transcript/F55A...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3939] opened 2015-06-09 16:20 UTC
<p>Server Error: 500 at <a href="http://www.wormbase.org/rest/widget/transcript/F55A8.2a.1/sequences">rest/widget/transcript/F55A8.2a.1/sequences</a></p><p></p><p>Error Message:<br> Caught exception in WormBase::Web::Controller::REST->widget "Can't call method "name" on an undefined value at /var/lib/jenkins/jobs/staging_build/workspace/lib/WormBase/API/Role/Sequence.pm line 1102." </p><p>What were you doing? <br />&nbsp;&nbsp;Trying to Look at the unspliced UTR sequence</p>

Reported by: neus***********************  (obscured for privacy)
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/600.1.17 (KHTML, like Gecko) Version/7.1 Safari/537.85.10

**Comment by tharris** [comment] 2015-06-09 16:31
Duplicate of #3936. Seems to be problem in flanking sequence method. @sibyl229 we can do hotfix for this if you find solution.

**Comment by sibyl229** [comment] 2015-06-09 17:16
@tharris Yup I committed the fix to hotfix branch. It's caused by the transcript occurring right at the border of a contig, so one of the flanking region doesn't exist. I think this can be merged to production, as these broken widgets aren't cached, so new cache will take their place once the API code works.

**Comment by tharris** [comment] 2015-06-10 18:37
Fixed, user notified.

**Closed by tharris** 2015-06-10 18:37 UTC
Labels: Bug Report, HelpDesk
