### ISSUE TITLE
Hi,
Using WormMine I create a list of genes (using...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6806] opened 2018-12-21 10:16 UTC
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi,
Using WormMine I create a list of genes (using WormBase ID) and to have phenotype information from alleles I select the columns Alleles -&gt; WormBase ID and Phentotype -&gt; Phenotype Name. I do the same (but separately) to have the information of the phenotypes that have been tested but not observed, in that case I selected Phenotype_not observed -&gt; Phenotype Name.
I spot check the results and I noticed that from a list of genes the info retrieved for WBGene00044341 is partial: I do not get the allele phenotype data for this gene (WBVar02147159), but yes the one for the phenotype not observed (WBVar00251936). 
Many thanks for your help
Paula

**Reported by:** Paul****** (paul****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/species/c_elegans/variation/WBVar00251936#026-45-3">https://www.wormbase.org/species/c_elegans/variation/WBVar00251936#026-45-3</a>
**Browser:** Chrome 71.0.3578.98

**Comment by chris-grove** [comment] 2018-12-21 16:38
Unfortunately, there is a known problem in WormMine in which alleles that map to multiple genes are only getting associated (in WormMine) to a single gene from the list. In the case of WBVar02147159 (tm8994), this allele is an 85 kb deletion predicted to affect 16 genes:


https://www.wormbase.org/species/c_elegans/variation/WBVar02147159#02-45-10-4


In WormMine, however, this allele is only getting associated with a single gene WBGene00197536 (M01G5.9) and not WBGene00044341. Our WormMine developer, Paulo Nuin (CC'ed), can provide an update on the progress on fixing this issue.


So, for now please be aware of alleles that affect (or potentially affect) multiple genes and this issue in WormMine.

**Comment by chris-grove** [comment] 2018-12-21 16:41
Duplicate of 
https://github.com/WormBase/website/issues/6141
Will close

**Closed by chris-grove** 2018-12-21 16:41 UTC
Labels: HelpDesk, source: offline chat
