### ISSUE TITLE
 Server Error: 500 at  tools/ontology_browser/show...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7098] opened 2019-05-07 09:27 UTC
*Submitted from the feedback form on the WormBase website.*

<p>Server Error: 500 at <a href="http://wormbase.org/tools/ontology_browser/show_genes?focusTermName=morphology%20variant&amp;focusTermId=WBPhenotype:0000520">tools/ontology_browser/show_genes</a></p><p>
</p><p>Error Message:<br> Caught exception in WormBase::Web::Controller::Tools-&gt;tools "malformed JSON string, neither tag, array, object, number, string or atom, at character offset 134552 (before "(end of string)") at /usr/local/wormbase/website/lib/WormBase/API/Service/ontology_browser.pm line 282." </p><p>What were you doing? <br />&nbsp;&nbsp;I was trying to find genes associated with a specific phenotype (seam cell fusion variant) by navigating through the Ontology Browser. Please help, thank you.</p>

**Reported by:** Chlo* (cyfu*******************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/ontology_browser/show_genes">/tools/ontology_browser/show_genes</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36

**Comment by chris-grove** [comment] 2019-05-07 19:55
My email to user:
"""
Apologies for the error. If you're still encountering the error, could you tell us exactly how you came to the error message so we can try to reproduce on our end?
"""

**Comment by Paul-Davis** [comment] 2019-07-01 15:04
@chris-grove  the rest endpoint seems to be working, if the user never replied, maybe this can be closed?

**Comment by chris-grove** [comment] 2019-07-01 16:57
Never heard back from user. Closing.

**Closed by chris-grove** 2019-07-01 16:57 UTC
Labels: Bug Report, HelpDesk
