### ISSUE TITLE
    What were you doing?   T...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3890] opened 2015-05-22 17:05 UTC
<p>&nbsp;&nbsp;</p><p>What were you doing? <br />&nbsp;&nbsp;Trying to open the tree display, it crashes.</p>

Reported by: Ranj*********** (ranj****************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:38.0) Gecko/20100101 Firefox/38.0

**Comment by tharris** [comment] 2015-05-22 17:12
Duplicate of #3885. I am currently working on this.

**Closed by tharris** 2015-05-22 17:12 UTC
Labels: Bug Report, HelpDesk
