### ISSUE TITLE
 Server Error: 500 at  tools/blast_blat/run   
  E...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5369] opened 2017-01-19 18:38 UTC
*Submitted from the feedback form on the WormBase website.*

<p>Server Error: 500 at <a href="http://www.wormbase.org/tools/blast_blat/run">tools/blast_blat/run</a></p><p>
</p><p>Error Message:<br> Caught exception in WormBase::Web::Controller::Tools-&gt;tools "read_file '/usr/local/wormbase/tmp/blast_blat/out_tFrkl.out.err' - sysopen: No such file or directory at /var/lib/jenkins/jobs/staging_build/workspace/lib/WormBase/API/Service/blast_blat.pm line 312." </p><p>What were you doing? <br />&nbsp;&nbsp;I am trying to use the Blast, which seems to be highly unstable these days. </p>

**Reported by:** Chao******** (cz21***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/blast_blat/run">/tools/blast_blat/run</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

**Comment by chris-grove** [comment] 2017-01-19 18:49
Hello Chaogu,


Thank you for reporting the error and apologies for the inconvenience.


Our web team is working to restore services. We will let you know when it is back up and running.


Thanks for your patience!


Chris Grove
WormBase

**Comment by chris-grove** [comment] 2017-01-19 18:49
Duplicate of #5366 
Closing

**Closed by chris-grove** 2017-01-19 18:49 UTC
Labels: Bug Report, HelpDesk

**Comment by chris-grove** [comment] 2017-01-20 19:12
Hello Chaogu,

 It appears that the BLAST service has been restored. Please let us know if you experience any more issues.

Best,

Chris
