### ISSUE TITLE
GBrowse link for C. elegans broken

### ISSUE THREAD

**Issue by brucebolt** [WormBase/website#3920] opened 2015-06-03 11:03 UTC
From the Species menu --> C. elegans --> Browse genome

There appears to be no default region defined, so the region =((CHR)):((START))-((END)) cannot be found
![screen shot 2015-06-03 at 12 03 13](https://cloud.githubusercontent.com/assets/6329861/7958566/889f7e1c-09e8-11e5-99fe-b8dd6d29b30f.png)

**Comment by scottcain** [comment] 2015-06-03 15:58
I don't think this is a general problem with GBrowse on WormBase.  I just tested with two browsers that had never been to WormBase before (on a newly created virtual machine) and GBrowse went to the default initial region.  GBrowse "remembers" the last place you were in a browser with a cookie, and perhaps something happened to that cookie.

**Comment by tharris** [comment] 2015-06-03 18:53
Yes, the initial landmark is set to 

initial landmark = III:9060076..9071680

The "=((CHR)):((START))-((END))" is really odd...

**Comment by paulwsternberg** [comment] 2015-06-03 19:36
Scott
Would you please write a few sentences about jvrowse status for wb progress report.
Thanks!!!

Paul

**Comment by brucebolt** [comment] 2015-06-03 19:48
I just tried again on my home computer and get taken to III:9060076..9071680.

On my work computer, I still get the =((CHR)):((START))-((END)).  After clearing cookies, I am taken to the default region.

**Comment by khowe** [comment] 2015-06-03 20:03
Just to support you @brucebolt , I too saw this behaviour a few days ago. But after clearing "=((CHR)):((START))-((END))" and inserting a real region (and navigating to it), I could not reproduce the problem (which is why I didn't create a ticket).

**Comment by tharris** [comment] 2015-06-03 20:31
And you guys are navigating to the browser from naive browsers that have never visited before? What platform / browser?

**Comment by khowe** [comment] 2015-06-03 20:35
For me, this was chrome on a Mac. But I had of course used the Gbrowse many times before from the same platform. The "=((CHR)):((START))-((END))" problem suddenly appeared for me one day, I manually cleared in in the way described above, and haven't seen it again since.

**Comment by brucebolt** [comment] 2015-06-04 16:26
Firefox on a Mac for me.  Visited WormBase GBrowse several times before on that browser without clearing cookies.

**Comment by scottcain** [comment] 2015-06-11 13:30
I think this was a transient problem and not much that can be done on our end to fix it, so I'm closing this.

**Closed by scottcain** 2015-06-11 13:30 UTC
Labels: Webteam
