### ISSUE TITLE
 Server Error: 500 at  tools/blast_blat/run   
  E...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5081] opened 2016-09-07 21:52 UTC
*Submitted from the feedback form on the WormBase website.*

<p>Server Error: 500 at <a href="http://www.wormbase.org/tools/blast_blat/run">tools/blast_blat/run</a></p><p>
</p><p>Error Message:<br> Caught exception in WormBase::Web::Controller::Tools-&gt;tools "read_file '/usr/local/wormbase/tmp/blast_blat/out_BrdiJ.out.err' - sysopen: No such file or directory at /var/lib/jenkins/jobs/staging_build/workspace/lib/WormBase/API/Service/blast_blat.pm line 312." </p><p>What were you doing? <br />&nbsp;&nbsp;blasting a nt sequence</p>

**Reported by:** jomo***************
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/blast_blat/run">/tools/blast_blat/run</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:48.0) Gecko/20100101 Firefox/48.0

**Comment by chris-grove** [comment] 2016-09-07 22:10
Hi jomontoyo,


 It looks like there must have been a temporary hiccup with the BLAST tool. Could you give it another try and let us know if you still encounter an error?


Thanks!


Chris Grove

WormBase

**Comment by vanaukenk** [comment] 2016-09-08 15:01
Hi,
I received the same error message this morning when trying to use BLAST:

Server Error: 500 at tools/blast_blat/run

Error Message:
Caught exception in WormBase::Web::Controller::Tools->tools "read_file '/usr/local/wormbase/tmp/blast_blat/out_EbFuU.out.err' - sysopen: No such file or directory at /var/lib/jenkins/jobs/staging_build/workspace/lib/WormBase/API/Service/blast_blat.pm line 312."

**Comment by chris-grove** [comment] 2016-09-12 18:00
BLAST is working now and I can't reproduce any problems. Closing.

**Closed by chris-grove** 2016-09-12 18:00 UTC
Labels: Bug Report, HelpDesk
