### ISSUE TITLE
Hi, just wondering how do I retrieve all genes fro...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5651] opened 2017-06-01 07:36 UTC
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi, just wondering how do I retrieve all genes fro the specific neuron(like I5)?

best 
Kevin

**Reported by:** kevi* (hang***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/all/anatomy_term/WBbt:0003953">http://www.wormbase.org/species/all/anatomy_term/WBbt:0003953</a>
**Browser:** Firefox 53.0

**Comment by chris-grove** [comment] 2017-06-01 14:52
Duplicate of #5650

**Closed by chris-grove** 2017-06-01 14:52 UTC
Labels: HelpDesk, source: offline chat
