### ISSUE TITLE
  Is the c elegans genome build WBCel23...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5878] opened 2017-09-28 06:16 UTC
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Is the c elegans genome build WBCel235 same as ce11? If not, which genome build is ce11?</p>

**Reported by:** Srav*************** (nsps***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/603.3.8 (KHTML, like Gecko) Version/10.1.2 Safari/603.3.8

**Comment by scottcain** [comment] 2017-09-28 13:43
Duplicate of #5878

**Closed by scottcain** 2017-09-28 13:43 UTC
Labels: HelpDesk
