### ISSUE TITLE
  Genetics Map is not working I get " S...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5425] opened 2017-02-16 16:19 UTC
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Genetics Map is not working<br/>I get " Sorry! an error has occurred. Gateway Time-out"<br/>I tried Mac and PC with explorer, chrome and Safari browsers </p>

**Reported by:** sari*********** (sari*********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

**Comment by tuli** [comment] 2017-02-21 10:07
Duplicate of #5428 Resolved.

**Closed by tuli** 2017-02-21 10:07 UTC
Labels: Everything's broken!, HelpDesk
