### ISSUE TITLE
 Server Error: 500 at  rest/widget/gene/WBGene0001...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7106] opened 2019-05-07 18:06 UTC
*Submitted from the feedback form on the WormBase website.*

<p>Server Error: 500 at <a href="http://wormbase.org/rest/widget/gene/WBGene00012802/gene_ontology">rest/widget/gene/WBGene00012802/gene_ontology</a></p><p></p><p>Error Message:<br> undef error - hash- or arrayref expected (not a simple scalar, use allow_nonref to allow this) at (eval 3577) line 4.<br> </p>

**Reported by:** Anon***** (tahs******************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0

**Comment by a8wright** [comment] 2019-05-25 03:46
@sibyl229 I just went to the website and it looks like this one is working now. I don't recognize the error. I am guessing it was a template or javascript issue.

**Comment by Paul-Davis** [comment] 2019-07-01 15:03
Confirmed, the rest endpoint returns the GO data now.....closing

**Closed by Paul-Davis** 2019-07-01 15:03 UTC
Labels: Bug Report, HelpDesk
