### ISSUE TITLE
 Server Error: 500 at  rest/widget/rearrangement/h...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6204] opened 2018-02-22 18:21 UTC
*Submitted from the feedback form on the WormBase website.*

<p>Server Error: 500 at <a href="http://www.wormbase.org/rest/widget/rearrangement/hT2[bli-4(e937)%20let-%3F(q782)%20qIs48]/overview">rest/widget/rearrangement/hT2[bli-4(e937)%20let-%3F(q782)%20qIs48]/overview</a></p><p>
</p><p>Error Message:<br> Caught exception in WormBase::Web::Controller::REST-&gt;widget "http://datomic-to-catalyst-ws262.us-east-1.elasticbeanstalk.com/rest/widget/rearrangement/hT2[bli-4(e937) let-?(q782) qIs48]/overview failed with 400 at /var/lib/jenkins/jobs/staging_build/workspace/lib/WormBase/Web/Controller/REST.pm line 919." </p><p>What were you doing? <br />&nbsp;&nbsp;looking up bli-4</p>

**Reported by:** Jack******* (jhel*************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//rest/widget/rearrangement/hT2[bli-4(e937) let-?(q782) qIs48]/overview">/rest/widget/rearrangement/hT2[bli-4(e937) let-?(q782) qIs48]/overview</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36

**Comment by sibyl229** [comment] 2018-02-22 18:27
Duplicate of https://github.com/WormBase/website/issues/6163.
Fixed on staging: https://staging.wormbase.org/species/all/rearrangement/hT2[bli-4(e937)%20let-%3F(q782)%20qIs48]#0--10

**Closed** 2019-03-13 11:15 UTC
Labels: Bug Report, HelpDesk
