### ISSUE TITLE
Hi, 
I'm not able to view information on Worm Base...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6150] opened 2018-01-29 19:45 UTC
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi, 
I'm not able to view information on Worm Base pages in Firefox. It seems to be viewed fine in Safari.

**Reported by:** Jona*********** (jrum**************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/strain/VC744">http://www.wormbase.org/species/c_elegans/strain/VC744</a>
**Browser:** Firefox 58.0

**Comment by sibyl229** [comment] 2018-01-30 17:14
duplicate of #6135

**Comment by gw3** [comment] 2018-02-06 09:28
Duplicate issue #6135 is closed: Fixed on staging now.

**Closed by gw3** 2018-02-06 09:28 UTC
Labels: HelpDesk, Webteam, source: offline chat
