### ISSUE TITLE
 Server Error: 500 at  rest/widget/rearrangement/e...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5846] opened 2017-09-10 22:14 UTC
*Submitted from the feedback form on the WormBase website.*

<p>Server Error: 500 at <a href="http://www.wormbase.org/rest/widget/rearrangement/eDf19/overview">rest/widget/rearrangement/eDf19/overview</a></p><p></p><p>Error Message:<br> Caught exception in WormBase::Web::Controller::REST->widget "http://datomic-to-catalyst-ws260.us-east-1.elasticbeanstalk.com/rest/widget/rearrangement/eDf19/overview failed with 500 at /var/lib/jenkins/jobs/staging_build/workspace/lib/WormBase/Web/Controller/REST.pm line 919." </p>

**Reported by:** Albe********* (ahin****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (X11; CrOS armv7l 9592.85.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.112 Safari/537.36

**Comment by sibyl229** [comment] 2017-09-12 17:00
related to #5840

**Comment by a8wright** [comment] 2017-09-13 14:10
This is now fixed in production. 

@khowe I think you might be interested in the cause
The reason that the uri was failing was because for this rearrangement, when I get the array from :rearrangement/pos-neg-data and then get :pos-neg-data/calculation on each one, there were two that were nil instead of positive or negative. I am not sure if it is logical to have some be nil but I thought you should be aware. Going forward, the website will function without error.. even if it is not defined.

**Closed by a8wright** 2017-09-13 14:10 UTC
Labels: Bug Report, HelpDesk
