### ISSUE TITLE
 Server Error: 500 at  rest/widget/gene/WBGene0000...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3900] opened 2015-05-26 19:37 UTC
<p>Server Error: 500 at <a href="http://www.wormbase.org/rest/widget/gene/WBGene00001340/sequences">rest/widget/gene/WBGene00001340/sequences</a></p><p></p><p>Error Message:<br> Caught exception in WormBase::Web::Controller::REST->widget "Can't call method "length" on an undefined value at /var/lib/jenkins/jobs/staging_build/workspace/lib/WormBase/API/Object/Gene.pm line 1695." </p>

Reported by: ruby**************  (obscured for privacy)
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.89 Safari/537.36

**Comment by xdwang** [comment] 2015-05-28 13:26
data looks good on staging though

**Comment by xdwang** [comment] 2015-05-28 13:33
Hi,

We will look into the issue. At the same time, you can use this page for the information:

http://staging.wormbase.org/species/c_elegans/gene/WBGene00001340#01-f-3 <http://staging.wormbase.org/species/c_elegans/gene/WBGene00001340#01-f-3>

Sorry for any inconvenience.

Xiaodong Wang
wormbase help desk officer


> On May 26, 2015, at 3:37 PM, no-reply@wormbase.org wrote:
> 
> Bug Report 
> Server Error: 500 at rest/widget/gene/WBGene00001340/sequences <http://www.wormbase.org/rest/widget/gene/WBGene00001340/sequences>
> 
> Error Message:
> Caught exception in WormBase::Web::Controller::REST->widget "Can't call method "length" on an undefined value at /var/lib/jenkins/jobs/staging_build/workspace/lib/WormBase/API/Object/Gene.pm line 1695." 
> 
> Submitted From: 
>   support /tools/support <http://www.wormbase.org//tools/support>
> This issue has been assigned ticket number: #3900. Follow progress on our issue tracker <https://github.com/WormBase/website/issues/3900>.
> 
> 
> Reported by: rubybtng@yahoo.com <mailto:rubybtng@yahoo.com> 
> 26 May 15 19:40 
> 
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.89 Safari/537.36 
> 
> This question was reported via the web interface at wormbase.org <http://wormbase.org/>. You can also email us <mailto:help@wormbase.org> directly.
> 
> 
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: help" group.
> To post to this group, send email to help@wormbase.org <mailto:help@wormbase.org>
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org <mailto:help+unsubscribe@wormbase.org>
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en <http://groups.google.com/a/wormbase.org/group/help?hl=en>
> 
> 
> To unsubscribe from this group and stop receiving emails from it, send an email to help+unsubscribe@wormbase.org <mailto:help+unsubscribe@wormbase.org>.

Xiaodong Wang, Ph.D
Wormbase Curator
626-395-8079
Biology Division
California Institute of Technology
1200 E. California Blvd
Pasadena, CA 91125

**Comment by tharris** [comment] 2015-05-29 10:33
Duplicate of #3801. This was a data problem with WS247 that Hinxton finxed in WS248.

**Closed by tharris** 2015-05-29 10:33 UTC
Labels: Bug Report, HelpDesk, Webteam
