### ISSUE TITLE
  I was trying to BLAST and then look a...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3591] opened 2015-02-05 21:11 UTC
<p>&nbsp;&nbsp;I was trying to BLAST and then look at the alignment of my worm's sequence against the "Genome View," but the page lacks my hit.<br/>And the following message appears at the bottom of the screen:<br/>Can't connect to www.wormbase.org:80 (Bad hostname) LWP::Protocol::http::Socket: Bad hostname 'www.wormbase.org' at /usr/share/perl5/LWP/Protocol/http.pm line 51. <br/>Thanks!</p>

Reported by: Elic********** (elic**********************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Windows NT 6.1; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0

**Comment by kyook** [comment] 2015-02-05 23:35
Hi Elicia,

Sorry to hear you are having trouble getting the information you want.
Would you let me know if you are still having trouble? Before you
check again, you may want to clear your browser cache.  If you are
still having trouble, please let me know what you are trying to BLAST
so we can be sure things are working before getting back to you.

Best,
Karen

On Thu, Feb 5, 2015 at 1:11 PM,  <no-reply@wormbase.org> wrote:
> Bug Report
>
>   I was trying to BLAST and then look at the alignment of my worm's sequence
> against the "Genome View," but the page lacks my hit.
> And the following message appears at the bottom of the screen:
> Can't connect to www.wormbase.org:80 (Bad hostname)
> LWP::Protocol::http::Socket: Bad hostname 'www.wormbase.org' at
> /usr/share/perl5/LWP/Protocol/http.pm line 51.
> Thanks!
>
> Submitted From:
>   support /tools/support
>
> This issue has been assigned ticket number: #3591. Follow progress on our
> issue tracker.
>
> Reported by: Elicia Preston (eliciap@mail.med.upenn.edu)
> 05 Feb 15 21:12
>
> Mozilla/5.0 (Windows NT 6.1; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0
>
> This question was reported via the web interface at wormbase.org. You can
> also email us directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase: help"
> group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>



-- 
~~~~
Karen Yook

Curator
WormBase Caltech
Tel: 626.395.5878
e-mail: kyook@caltech.edu
e-mail: kyook@wormbase.org
skype name: wbkaren

**Comment by kyook** [comment] 2015-02-09 21:43
Hi Elici,

Again, apologies for these troubles.  We have had similar reports of
the same problem since you wrote in. The webteam and GBrowse team have
been alerted so I hope it won't be too long until the problems are
fixed.  Someone should be in touch once the problem is fixed.

Again, I'm sorry we weren't able to address these bugs in time to help you out.

Best wishes,
Karen

On Mon, Feb 9, 2015 at 1:25 PM, Elicia Preston
<eliciap@mail.med.upenn.edu> wrote:
>
> Karen,
>
> Thank you for your help.
> I cleared the cache, tried multiple web-browsers, and the then tried a new computer.
> Still the same bug of not being able to visualize to hit on the "genome view,"
> which would be nice for lab meeting but not essential since I can do it (very slowly) manually with the base-numbers provided.
>
> Thanks again and good luck,
>
> Elicia Preston
> Research Scientist
> Murray Lab, UPenn Genetics & PGFI
> 440 Clinical Research Building
> 415 Curie Boulevard
> Philadelphia, PA 19104-6145
> Lab: (215) 746-4363
>
> ----- Original Message -----
> From: Karen Yook <kyook@wormbase.org>
> To: eliciap@mail.med.upenn.edu
> Cc: help@wormbase.org, WormBase/website <reply@reply.github.com>
> Sent: Thu, 05 Feb 2015 18:35:12 -0500 (EST)
> Subject: Re: [wormbase-help] Bug Report: I was trying to BLAST and then look a... (Elicia Preston)
>
> Hi Elicia,
>
> Sorry to hear you are having trouble getting the information you want.
> Would you let me know if you are still having trouble? Before you
> check again, you may want to clear your browser cache.  If you are
> still having trouble, please let me know what you are trying to BLAST
> so we can be sure things are working before getting back to you.
>
> Best,
> Karen
>
> On Thu, Feb 5, 2015 at 1:11 PM,  <no-reply@wormbase.org> wrote:
>> Bug Report
>>
>>   I was trying to BLAST and then look at the alignment of my worm's sequence
>> against the "Genome View," but the page lacks my hit.
>> And the following message appears at the bottom of the screen:
>> Can't connect to www.wormbase.org:80 (Bad hostname)
>> LWP::Protocol::http::Socket: Bad hostname 'www.wormbase.org' at
>> /usr/share/perl5/LWP/Protocol/http.pm line 51.
>> Thanks!
>>
>> Submitted From:
>>   support /tools/support
>>
>> This issue has been assigned ticket number: #3591. Follow progress on our
>> issue tracker.
>>
>> Reported by: Elicia Preston (eliciap@mail.med.upenn.edu)
>> 05 Feb 15 21:12
>>
>> Mozilla/5.0 (Windows NT 6.1; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0
>>
>> This question was reported via the web interface at wormbase.org. You can
>> also email us directly.
>>
>> --
>> --
>> You received this message because you are subscribed to the "WormBase: help"
>> group.
>> To post to this group, send email to help@wormbase.org
>> To unsubscribe from this group, send email to
>> help+unsubscribe@wormbase.org
>> For more options, visit this group at
>> http://groups.google.com/a/wormbase.org/group/help?hl=en
>>
>
>
>
> --
> ~~~~
> Karen Yook
>
> Curator
> WormBase Caltech
> Tel: 626.395.5878
> e-mail: kyook@caltech.edu
> e-mail: kyook@wormbase.org
> skype name: wbkaren
>



-- 
~~~~
Karen Yook

Curator
WormBase Caltech
Tel: 626.395.5878
e-mail: kyook@caltech.edu
e-mail: kyook@wormbase.org
skype name: wbkaren

**Comment by kyook** [comment] 2015-02-10 18:55
I'll let the webteam know.  Glad it was fixed in time!

Good luck with your meeting.

Karen

On Tue, Feb 10, 2015 at 10:36 AM, Elicia Preston
<eliciap@mail.med.upenn.edu> wrote:
>
> Karen,
>
> It's working now, thanks for fixing it!!!
>
> Thanks,
> Elicia Preston
> Research Scientist
> Murray Lab, UPenn Genetics & PGFI
> 440 Clinical Research Building
> 415 Curie Boulevard
> Philadelphia, PA 19104-6145
> Lab: (215) 746-4363
>
> ----- Original Message -----
> From: Elicia Preston <eliciap@mail.med.upenn.edu>
> To: kyook@wormbase.org
> Sent: Mon, 09 Feb 2015 16:25:43 -0500 (EST)
> Subject: Re: [wormbase-help] Bug Report: No Hits on Genome View. (Elicia Preston)
>
>
> Karen,
>
> Thank you for your help.
> I cleared the cache, tried multiple web-browsers, and the then tried a new computer.
> Still the same bug of not being able to visualize to hit on the "genome view,"
> which would be nice for lab meeting but not essential since I can do it (very slowly) manually with the base-numbers provided.
>
> Thanks again and good luck,
>
> Elicia Preston
> Research Scientist
> Murray Lab, UPenn Genetics & PGFI
> 440 Clinical Research Building
> 415 Curie Boulevard
> Philadelphia, PA 19104-6145
> Lab: (215) 746-4363
>
> ----- Original Message -----
> From: Karen Yook <kyook@wormbase.org>
> To: eliciap@mail.med.upenn.edu
> Cc: help@wormbase.org, WormBase/website <reply@reply.github.com>
> Sent: Thu, 05 Feb 2015 18:35:12 -0500 (EST)
> Subject: Re: [wormbase-help] Bug Report: I was trying to BLAST and then look a... (Elicia Preston)
>
> Hi Elicia,
>
> Sorry to hear you are having trouble getting the information you want.
> Would you let me know if you are still having trouble? Before you
> check again, you may want to clear your browser cache.  If you are
> still having trouble, please let me know what you are trying to BLAST
> so we can be sure things are working before getting back to you.
>
> Best,
> Karen
>
> On Thu, Feb 5, 2015 at 1:11 PM,  <no-reply@wormbase.org> wrote:
>> Bug Report
>>
>>   I was trying to BLAST and then look at the alignment of my worm's sequence
>> against the "Genome View," but the page lacks my hit.
>> And the following message appears at the bottom of the screen:
>> Can't connect to www.wormbase.org:80 (Bad hostname)
>> LWP::Protocol::http::Socket: Bad hostname 'www.wormbase.org' at
>> /usr/share/perl5/LWP/Protocol/http.pm line 51.
>> Thanks!
>>
>> Submitted From:
>>   support /tools/support
>>
>> This issue has been assigned ticket number: #3591. Follow progress on our
>> issue tracker.
>>
>> Reported by: Elicia Preston (eliciap@mail.med.upenn.edu)
>> 05 Feb 15 21:12
>>
>> Mozilla/5.0 (Windows NT 6.1; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0
>>
>> This question was reported via the web interface at wormbase.org. You can
>> also email us directly.
>>
>> --
>> --
>> You received this message because you are subscribed to the "WormBase: help"
>> group.
>> To post to this group, send email to help@wormbase.org
>> To unsubscribe from this group, send email to
>> help+unsubscribe@wormbase.org
>> For more options, visit this group at
>> http://groups.google.com/a/wormbase.org/group/help?hl=en
>>
>
>
>
> --
> ~~~~
> Karen Yook
>
> Curator
> WormBase Caltech
> Tel: 626.395.5878
> e-mail: kyook@caltech.edu
> e-mail: kyook@wormbase.org
> skype name: wbkaren
>
>



-- 
~~~~
Karen Yook

Curator
WormBase Caltech
Tel: 626.395.5878
e-mail: kyook@caltech.edu
e-mail: kyook@wormbase.org
skype name: wbkaren

**Closed** 2015-02-10 18:57 UTC
Labels: Bug Report, gbrowse, HelpDesk
