### ISSUE TITLE
ftp://ftp.wormbase.org/pub/wormbase/species/c_eleg...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4747] opened 2016-04-14 22:22 UTC
*Help Desk query collected when no chat operators were online. Follow up required.*

ftp://ftp.wormbase.org/pub/wormbase/species/c_elegans/sequence/transcripts/c_elegans.PRJNA13758.WS250.CDS_transcripts.fa.gz

**Reported by:** Joyc* (qzha***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/#01-23-6">https://www.wormbase.org/#01-23-6</a>
**Browser:** Chrome 49.0.2623.112

**Comment by azurebrd** [comment] 2016-04-14 22:27
Duplicate of #4748

**Closed by azurebrd** 2016-04-14 22:27 UTC
Labels: HelpDesk, source: offline chat
