### ISSUE TITLE
 Server Error: 500 at  tools/blast_blat/run   
  E...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5061] opened 2016-08-30 16:36 UTC
*Submitted from the feedback form on the WormBase website.*

<p>Server Error: 500 at <a href="http://www.wormbase.org/tools/blast_blat/run">tools/blast_blat/run</a></p><p>
</p><p>Error Message:<br> Caught exception in WormBase::Web::Controller::Tools-&gt;tools "read_file '/usr/local/wormbase/tmp/blast_blat/out_95vps.out.err' - sysopen: No such file or directory at /var/lib/jenkins/jobs/staging_build/workspace/lib/WormBase/API/Service/blast_blat.pm line 312." </p><p>What were you doing? <br />&nbsp;&nbsp;blasting a mouse sequence</p>

**Reported by:** mark****************
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/blast_blat/run">/tools/blast_blat/run</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36

**Comment by chris-grove** [comment] 2016-08-30 19:39
Hi Mark,


 Thanks for reporting the problem and apologies for the inconvenience. Our web team is working to restore BLAST functionality now. We'll let you know when it's back up and running.


Thanks,


Chris Grove

WormBase

**Comment by chris-grove** [comment] 2016-08-30 19:40
Duplicate of #5063 Closing

**Closed by chris-grove** 2016-08-30 19:40 UTC
Labels: Bug Report, HelpDesk

**Comment by chris-grove** [comment] 2016-08-30 20:58
Emailed user about restored services
