### ISSUE TITLE
 Server Error: 500 at  rest/widget/gene/WBGene0022...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5112] opened 2016-09-22 14:12 UTC
*Submitted from the feedback form on the WormBase website.*

<p>Server Error: 500 at <a href="http://www.wormbase.org/rest/widget/gene/WBGene00220628/sequences">rest/widget/gene/WBGene00220628/sequences</a></p><p></p><p>Error Message:<br> Caught exception in WormBase::Web::Controller::REST->widget "Could not connect to database gff b_malayi_PRJNA10729_WS254, host: ip-10-0-0-184" </p><p>What were you doing? <br />&nbsp;&nbsp;accessing that gene page</p>

**Reported by:** Mich*********** (mich************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36

**Comment by scottcain** [comment] 2016-09-22 14:56
There was a configuration problem in production that I fixed, however there is still a problem with the B. malayi in GBrowse.  For example, when I look for Bma-unc-9, I get a gene page but the images that should come from GBrowse are broken and when I look at GBrowse proper, it seems that it can't find Bm_v4_ChrX_scaffold_001 (the fact that one of the examples provided has "v3" in the name is a secondary issue that should be fixed).  I'm not sure what the problem is yet but it does not extend to 255/staging, where GBrowse can find Bm_v4_ChrX_scaffold_001.

**Comment by scottcain** [comment] 2016-09-22 15:04
the 254 B. malayi database is broken: "Table 'b_malayi_PRJNA10729_WS254.meta' doesn't exist" @tharris

**Comment by scottcain** [comment] 2016-09-27 14:02
Since this works on 255 and it will be live in a week or two, we won't be fixing this.

**Closed by scottcain** 2016-09-27 14:02 UTC
Labels: Bug Report, HelpDesk, Webteam
