### ISSUE TITLE
the search box on the upper right corner behave di...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4225] opened 2015-09-30 10:46 UTC
*Help Desk query collected when no chat operators were online. Follow up required.*

the search box on the upper right corner behave different between the gbrowse and the rest of the page.

 Is that intended?
    
**Reported by:** Mich*** (mich************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/b_malayi/gene/WBGene00228713#06-9fd-3">http://www.wormbase.org/species/b_malayi/gene/WBGene00228713#06-9fd-3</a>
**Browser:** Chrome 45.0.2454.101

**Comment by chris-grove** [comment] 2015-09-30 17:06
@tharris @sibyl229 
Confirmed. The search box on the GBrowse page is not working properly. I can't select any other data type to search for, and if I search for anything by typing and pressing the ENTER key, the page just reloads the same GBrowse page. Only if I type something and it comes up in the auto-suggest list below the search field and I click on the auto-suggest term, will it load that page.

**Comment by chris-grove** [comment] 2015-09-30 17:23
@epaule  sorry, I didn't realize this was from you

**Comment by scottcain** [comment] 2015-09-30 17:53
@sibyl229 GBrowse pulls the WormBase banner and stuff by getting http://www.wormbase.org/header?desktop=true.  Is that what everything else does, or is it just GBrowse.  If so, is it something with the content at the URL is different from what the rest of WormBase users?  There are a few JS errors when the GBrowse page loads:
```
Uncaught TypeError: $jq(...).on is not a function   
Uncaught ReferenceError: WB is not defined
```
that don't occur when the main page is loaded.

**Comment by sibyl229** [comment] 2015-10-02 16:04
Hi @scottcain right, thanks for the hint. This was the issue we fixed last week: the on function not available for the jquery version used by GBrowse.

Hi @chris-grove Could you try the search box on GBrowse page from staging? The issue was caused by an error in the website javascript code, which has been fixed on staging.

**Comment by chris-grove** [comment] 2015-10-02 18:53
@sibyl229  Yes, it's now fixed on staging. Shall I close the ticket?

**Comment by sibyl229** [comment] 2015-10-02 19:52
Thanks @chris-grove. I will close this then.

**Closed by sibyl229** 2015-10-02 19:52 UTC
Labels: bug, HelpDesk, source: offline chat, UI-app behavior, Under testing, Webteam
