### ISSUE TITLE
Species display issue in gene page Homology widget "Other orthologs" table

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#6722] opened 2018-11-06 19:53 UTC
On the C27B7.7 gene page:

https://www.wormbase.org/species/c_elegans/gene/WBGene00007764#0-6-10

In the Homology widget, in the "Other orthologs" table, several orthologs are listed as having species:

"genus:Allspecies:"

![screen shot 2018-11-06 at 2 49 04 pm](https://user-images.githubusercontent.com/611382/48089920-95a88b00-e1d3-11e8-8615-94671c0b352f.png)

The entries in this case are:

PRJNA51225:Cang_2012_03_13_00204.g6936
PRJNA384657:Cni-C27B7.7
PRJNA384657:Cnig_chr_IV.g13096
PRJNA194557:Csp5_scaffold_00120.g4869
PRJNA53597:Csp11.Scaffold629.g15216

So it appears as we should have species information for each of these genes. Is this a bug?

**Comment by epaule** [comment] 2018-11-07 09:34
duplicate of #6659 (which contains the patch)

**Closed by epaule** 2018-11-07 09:34 UTC
Labels: UI-data display, bug
