### ISSUE TITLE
Chris: Hello Gabby, how can I help? visitor_name (...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5683] opened 2017-06-12 14:05 UTC
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

Chris: Hello Gabby, how can I help?</br>visitor_name (visitor_email): Hi, i wanted to find out, what are the alleles for the dpy-5 &amp; dpy-10 gene?</br>visitor_name (visitor_email): or how do i find them</br>Chris: OK, the best place to look is in the "Genetics" widget (data box) on the respective gene pages</br>Chris: http://www.wormbase.org/species/c_elegans/gene/WBGene00001067#04--10</br>visitor_name (visitor_email): ok awesome! also where would i find modes of inheritance?</br>Chris: That's the dpy-5 page with the Genetics widget</br>Chris: open</br>Chris: Do you mean like whether or not the allele is dominant or recessive?</br>visitor_name (visitor_email): yes in a sense... there are modes such as... autosomal recessive or x-linked dominant</br>Chris: OK, we only classify if alleles are dominant, semi-dominant, or recessive</br>Chris: You can find this on the allele page in the "Phenotypes" widget</br>visitor_name (visitor_email): alrighty</br>visitor_name (visitor_email): thanks so much for the help!</br>Chris: So if you look at the allele page for e61:</br>Chris: http://www.wormbase.org/species/c_elegans/variation/WBVar00142941#06--10</br>Chris: you can see in the annotation to the "dumpy" phenotype that this allele is considered semi-dominant</br>Chris: it's easiest if you open the allele page and the Phenotypes widget on that page and then do a text search on the page for "recessive", "dominant" or "semi dominant"</br>visitor_name (visitor_email): ok i'll definitely try that</br>Chris: or use the text search box inside the Phenotypes widget</br>Chris: OK, sounds good. You're welcome</br>Chris: Is there anything else I can help you with?</br>visitor_name (visitor_email): no sir</br>visitor_name (visitor_email): i appreciate the help!</br>Chris: OK, no problem. Have a nice day!</br>visitor_name (visitor_email): you too!</br>Chris: Thanks!

**Reported by:** gabb* (skyb****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00001065#0-9g-3">http://www.wormbase.org/species/c_elegans/gene/WBGene00001065#0-9g-3</a>
**Browser:** Safari 10.0.3

**Comment by chris-grove** [comment] 2017-06-12 14:28
Duplicate of #5682

**Closed by chris-grove** 2017-06-12 14:28 UTC
Labels: HelpDesk, source: online chat
