### ISSUE TITLE
Chris: Hello Stefan, how can I help? visitor_name ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4712] opened 2016-04-04 21:56 UTC
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

Chris: Hello Stefan, how can I help?</br>visitor_name (visitor_email): hello, i am wondering what happened to the natural variation section under the "genetics" tab</br>visitor_name (visitor_email): ..when looking at a gene</br>Chris: I think it may have been merged with polymorphisms, but let me take a look</br>visitor_name (visitor_email): polymorphisms is also gone</br>Chris: Hmmm, yes I see that</br>visitor_name (visitor_email): i noticed this two weeks ago</br>Chris: This may have changed with the latest WormBase release, WS252</br>Chris: Let me take a look at our internal records and see what I can find</br>visitor_name (visitor_email): great, thanks</br>Chris: no problem</br>Chris: Hi Stefan, this looks to be a bug</br>Chris: Apologies. Is there specific data I can get for you while we fix this?</br>visitor_name (visitor_email): it's not a big deal</br>visitor_name (visitor_email): i have other ways of accessing the data, this is just the most convenient for small tasks

**Reported by:** stef** (szdr**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00077563#0g6-49f-3">http://www.wormbase.org/species/c_elegans/gene/WBGene00077563#0g6-49f-3</a>
**Browser:** Chrome 49.0.2623.87

**Comment by chris-grove** [comment] 2016-04-04 22:03
Duplicate of #4711 
Closing

**Closed by chris-grove** 2016-04-04 22:03 UTC
Labels: HelpDesk, source: online chat
