### ISSUE TITLE
  ...save in JBrowse a svg file of the ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7225] opened 2019-07-18 16:53 UTC
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;...save in JBrowse a svg file of the tracks?<br/>I apologize for the clumsiness <br/>Thanks a lot!<br/>Ines</p>

**Reported by:** InÃ©********* (carr*****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36

**Comment by scottcain** [comment] 2019-07-22 17:47
Replied to user:

Hello Inés,

No need to apologize! Especially since it is I who should be apologizing to you, since JBrowse doesn't yet support SVG saving.  I think in the next year or so it will, but in the meantime, the only option is to make high resolution JPEG or PNG images (or, of course, use GBrowse to create an SVG).  To do that, you can click on the "Screenshot button" and experiment with the "zoom factor" option (though more than 4 is unlikely to make things much better) and with the width and height options to get the image to have good dimensions for the image you want to create.

I should mention that in addition to this limitation, another one is that tracks added via the "File" -> "Open track file or URL" aren't available to the Screenshot tool, which is potentially a painful limitation for a researcher.  Please let me know if neither of these options (JBrowse screenshot or GBrowse SVG) appeal to you, as there might be things I could do on our staging server to add tracks that you need to JBrowse so that you can screenshot those.

**Comment by chris-grove** [comment] 2019-07-25 19:21
Duplicate of #5623

**Comment by scottcain** [comment] 2020-01-15 18:39
I think it's safe to close this, since JBrowse 1 will never get this as a feature, and when we implement JBrowse 2, this feature will be coming along for the ride.

**Closed by scottcain** 2020-01-15 18:39 UTC
Labels: HelpDesk, How Do I ...?, feature request, jbrowse
