### ISSUE TITLE
 Server Error: 500 at  rest/widget/pcr_oligo/..AAA...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6277] opened 2018-03-23 14:42 UTC
*Submitted from the feedback form on the WormBase website.*

<p>Server Error: 500 at <a href="http://www.wormbase.org/rest/widget/pcr_oligo/..AAA28142/sequence">rest/widget/pcr_oligo/..AAA28142/sequence</a></p><p></p><p>Error Message:<br> Caught exception in WormBase::Web::Controller::REST->widget "Could not fetch object ..AAA28142, pcr_oligo at /var/lib/jenkins/jobs/staging_build/workspace/lib/WormBase/Web/Controller/REST.pm line 941." </p>

**Reported by:** elia**********************
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.162 Safari/537.36

**Comment by WenChenWormBase** [comment] 2018-03-26 17:06
duplicate of 6276

**Closed by WenChenWormBase** 2018-03-26 17:06 UTC
Labels: Bug Report, HelpDesk
