### ISSUE TITLE
 Server Error: 500 at  rest/widget/transcript/C46A...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4189] opened 2015-09-16 10:04 UTC
*Submitted from the feedback form on the WormBase website.*

<p>Server Error: 500 at <a href="http://www.wormbase.org/rest/widget/transcript/C46A5.10a/overview">rest/widget/transcript/C46A5.10a/overview</a></p><p></p><p>Error Message:<br> Caught exception in WormBase::Web::Controller::REST->widget "Can't call method "length" on an undefined value at /var/lib/jenkins/jobs/staging_build/workspace/lib/WormBase/API/Role/Sequence.pm line 475." </p>
    
**Reported by:** Dupu******* (d.du**********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36

**Comment by chris-grove** [comment] 2015-09-16 17:12
Likely duplicate of #4188

**Comment by chris-grove** [comment] 2015-09-16 17:12
Problem also exists on staging

**Comment by rankishore** [comment] 2015-09-25 17:01
Still broken, could @sibyl229 or @tharris, take a look, please

**Comment by rankishore** [comment] 2015-09-28 16:42
Following up with #4188, as same issue.

**Closed by rankishore** 2015-09-28 16:42 UTC
Labels: Bug Report, HelpDesk
