### ISSUE TITLE
 Server Error: 500 at  rest/widget/gene/WBGene0000...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3772] opened 2015-04-13 20:17 UTC
<p>Server Error: 500 at <a href="http://www.wormbase.org/rest/widget/gene/WBGene00001679/sequences">rest/widget/gene/WBGene00001679/sequences</a></p><p>
</p><p>Error Message:<br> Caught exception in WormBase::Web::Controller::REST-&gt;widget "Can't call method "length" on an undefined value at /var/lib/jenkins/jobs/staging_build/workspace/lib/WormBase/API/Object/Gene.pm line 1695." </p>

Reported by: ads0*************  (obscured for privacy)
Submitted From:  <a href="http://www.wormbase.org//rest/widget/gene/WBGene00001679/sequences">/rest/widget/gene/WBGene00001679/sequences</a>

Mozilla/5.0 (Windows NT 6.1; WOW64; rv:23.0) Gecko/20100101 Firefox/23.0

**Comment by chris-grove** [comment] 2015-04-13 20:57
Duplicate of #3773

**Closed by chris-grove** 2015-04-13 20:57 UTC
Labels: Bug Report, HelpDesk
