### ISSUE TITLE
WS266 FTP site sync

### ISSUE THREAD

**Issue by epaule** [WormBase/website#6646] opened 2018-09-21 16:06 UTC
basically not all files were copied over from EBI (notably the UCSC hub ones)

ftp://ftp.ebi.ac.uk/pub/databases/wormbase/releases/current-production-release/MULTI_SPECIES/
vs
ftp://ftp.wormbase.org/pub/wormbase/releases/WS266/MULTI_SPECIES/

======================
Hi Wormbase Web Developers,

I'm from the UCSC Genome Browser and we link users to your worm assembly data through our Track Hub feature. We recently have been unable to open one of your website's data files, specificallyftp://ftp.wormbase.org/pub/wormbase/releases/current-production-release/MULTI_SPECIES/hub/genomes.txt. You can see the errors on our Public Track Hub page [http://genome.ucsc.edu/cgi-bin/hgHubConnect?hubSearchTerms=wormbase#publicHubs]. We'd like to make sure researchers can access those files and use that data you're hosting. Are you aware that these files are no longer accessible?

Thank you!
Daniel Schmelter
UCSC Genome Browser

**Comment by tharris** [comment] 2018-09-21 18:49
Re-synced. And it looks like Daniel has confirmed. Closing.

**Closed by tharris** 2018-09-21 18:49 UTC
Labels: Webteam, data (problem)
