### ISSUE TITLE
 Server Error: 500 at  rest/widget/operon/CEOP3857...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4025] opened 2015-07-02 21:45 UTC
<p>Server Error: 500 at <a href="http://www.wormbase.org/rest/widget/operon/CEOP3857/location">rest/widget/operon/CEOP3857/location</a></p><p></p><p>Error Message:<br> Caught exception in WormBase::Web::Controller::REST->widget "Can't call method "seq_id" without a package or object reference at /var/lib/jenkins/jobs/staging_build/workspace/lib/WormBase/API/Role/Position.pm line 140." </p>

Reported by: vsla***********  (obscured for privacy)
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.124 Safari/537.36

**Comment by dasmoth** [comment] 2015-07-03 07:30
Thank you for writing to WormBase.

The operon you're looking for is obsolete because it has been merged with
CEOP3871 <http://www.wormbase.org/species/c_elegans/operon/CEOP3871#012--10>.
Some notes about operon history can be seen under "Curatorial remarks" in
the Overview widget.

Obsolete and merged operons don't have genomic coordinates defined in our
database, and therefore don't have a location -- although the fact that
you're seeing an error message here is a bug, which I believe will be fixed
in the next release.

Best wishes,

             Thomas.

**Comment by dasmoth** [comment] 2015-07-03 07:32
Duplicate of #3990, the pull request I sent should fix this tool.

**Closed** 2015-07-22 17:02 UTC
Labels: Bug Report, HelpDesk, Helped
