### ISSUE TITLE
  Hi, perhaps you are aware already but...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4856] opened 2016-05-27 10:50 UTC
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi,<br/>perhaps you are aware already but there seems to be an issue with the wormbrowser. As soon as you pass the mouse upon the browser screen, random windows (with info from the browser not requested) pop up without even clicking anywere...<br/>Cheers,<br/>Paola</p>

**Reported by:** p j (paol*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64; rv:46.0) Gecko/20100101 Firefox/46.0

**Comment by epaule** [comment] 2016-05-27 11:06
http://www.wormbase.org/tools/genome/gbrowse/c_elegans_PRJNA13758/?name=II%3A5717037..5724127

Actually, is the corresponging EST poping up I think... but without clicking them.

**Comment by scottcain** [comment] 2016-05-31 14:13
Could is bug be related to this (very annoying yet currently inexplicable) bug: https://github.com/WormBase/website/issues/2991 (which I had forgotten about) or is this a separate problem?  The link @epaule provided doesn't make it clear.

**Comment by epaule** [comment] 2016-05-31 14:15
most likely yes. It actually seems to be a onmouseover event on the EST track (but not the others)

**Comment by brucebolt** [comment] 2016-05-31 14:16
Oddly, I can only reproduce the issue on Chrome.  In Firefox (which the user was using), I don't get the popups.

**Comment by epaule** [comment] 2016-05-31 14:38
I think FireFox blocks the new tabs/popups by default.

**Comment by scottcain** [comment] 2016-06-02 17:47
Fixed on staging and will go live with 253 in a few days.  User contacted.

**Closed by scottcain** 2016-06-02 17:47 UTC
Labels: Bug Report, gbrowse, HelpDesk, Webteam
