### ISSUE TITLE
wormbase seems to be slow this week.... is it me o...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4356] opened 2015-11-10 21:01 UTC
*Help Desk query collected when no chat operators were online. Follow up required.*

wormbase seems to be slow this week.... is it me or you?

**Reported by:** Pete***** (pete*****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00006789#01ba-9e4d675fgih8-10-h8">http://www.wormbase.org/species/c_elegans/gene/WBGene00006789#01ba-9e4d675fgih8-10-h8</a>
**Browser:** Chrome 46.0.2490.80

**Comment by draciti** [comment] 2015-11-10 21:18
Hi Peter, thanks for reporting the issue. 
We are aware of it and our Webteam will look into it asap.
Daniela

**Comment by draciti** [comment] 2015-11-10 21:18
Duplicate of #4355

**Closed by draciti** 2015-11-10 21:18 UTC
Labels: HelpDesk, source: offline chat
