### ISSUE TITLE
  Reporting a time out  What were you d...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3639] opened 2015-02-26 11:27 UTC
<p>&nbsp;&nbsp;Reporting a time out</p><p>What were you doing? <br />&nbsp;&nbsp;Trying to look at eDf3 Rearrangement Summary page. The Overview widget timed out. </p>

Reported by: Mary********* (mary*********************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/600.3.18 (KHTML, like Gecko) Version/7.1.3 Safari/537.85.12

**Comment by tuli** [comment] 2015-02-26 11:34
Same on staging.

On 26 February 2015 at 11:27, WormBase Helpdesk <notifications@github.com>
wrote:

>   Reporting a time out
>
> What were you doing?
>   Trying to look at eDf3 Rearrangement Summary page. The Overview widget
> timed out.
>
> Reported by: Mary********* (mary*********************) (obscured for
> privacy))
> Submitted From: support /tools/support
> <http://www.wormbase.org//tools/support>
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/600.3.18
> (KHTML, like Gecko) Version/7.1.3 Safari/537.85.12
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WormBase/website/issues/3639>.
>



-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125

**Comment by sibyl229** [comment] 2015-03-06 17:29
duplicate of #3234 
Working on production now: http://www.wormbase.org/species/all/rearrangement/eDf3#0--10

**Closed by sibyl229** 2015-03-06 17:29 UTC
Labels: Bug Report, HelpDesk, Webteam
