### ISSUE TITLE
 Server Error: 500 at  tools/blast_blat/run   
  E...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5319] opened 2016-12-15 00:40 UTC
*Submitted from the feedback form on the WormBase website.*

<p>Server Error: 500 at <a href="http://www.wormbase.org/tools/blast_blat/run">tools/blast_blat/run</a></p><p>
</p><p>Error Message:<br> Caught exception in WormBase::Web::Controller::Tools-&gt;tools "read_file '/usr/local/wormbase/tmp/blast_blat/out_9npPE.out.err' - sysopen: No such file or directory at /var/lib/jenkins/jobs/staging_build/workspace/lib/WormBase/API/Service/blast_blat.pm line 312." </p><p>What were you doing? <br />&nbsp;&nbsp;i did blast using protein sewuence
</p>

**Reported by:** Uno (muno**********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/blast_blat/run">/tools/blast_blat/run</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0

**Comment by vanaukenk** [comment] 2016-12-15 13:46
Hi,


Thanks for writing to WormBase and our apologies for the inconvenience.


Can you please try the BLAST/BLAT tool again and let us know if you're still have any problems?


Best,

--Kimberly Van Auken

**Comment by sibyl229** [comment] 2016-12-15 23:26
Hi @tharris @vanaukenk It seems that the actual problem with BLAST is obscured/lost, because the error message here indicates failure to open/find the temporary error file that captures error generated by blast command line tool. Without being able to reproduce the exact problem, what I can do right now is try to fix the problem caused by the error capturing file, so we can reveal the problem produced by blast tool.

```perl
    my $result = system($command_line);
    if ($result) {
        warn "$out_file.err";
        my $err = slurp("$out_file.err");
    }
```

**Comment by vanaukenk** [comment] 2016-12-16 19:47
Thanks @sibyl229.
Shall I leave this ticket open for now, or would you prefer we close it and see if we get more information the next time an error occurs?

**Comment by WenChenWormBase** [comment] 2017-01-03 21:22
@sibyl229 I will leave this ticket to you. If you feel it can be closed now, please do so.

**Closed by WenChenWormBase** 2017-01-03 21:22 UTC
Labels: Bug Report, HelpDesk, URGENT, Webteam
