### ISSUE TITLE
 Server Error: 500 at  rest/widget/gene/WBGene0000...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4457] opened 2016-01-04 18:32 UTC
*Submitted from the feedback form on the WormBase website.*

<p>Server Error: 500 at <a href="http://www.wormbase.org/rest/widget/gene/WBGene00000915/phenotype">rest/widget/gene/WBGene00000915/phenotype</a></p><p></p><p>Error Message:<br> Caught exception in WormBase::Web::Controller::REST->widget "Can't call method "Name" on an undefined value at /var/lib/jenkins/jobs/staging_build/workspace/lib/WormBase/API/Role/Phenotype.pm line 143." </p><p>What were you doing? <br />&nbsp;&nbsp;Trying to access phenotype data for daf-21
</p>

**Reported by:** Geor************ (sutp*************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36

**Comment by chris-grove** [comment] 2016-01-04 19:26
@tharris  @sibyl229 
I think this may be a duplicate of #4454

**Comment by sibyl229** [comment] 2016-01-13 19:28
Todd has fixed this one, and deployed to live site http://www.wormbase.org/rest/widget/gene/WBGene00000915/phenotype

**Closed by sibyl229** 2016-01-13 19:28 UTC
Labels: Bug Report, HelpDesk
