### ISSUE TITLE
Protein domain graphics bug 

### ISSUE THREAD

**Issue by sibyl229** [WormBase/website#7197] opened 2019-06-28 15:24 UTC
Someone at the worm meeting pointed out this problem:

![Screen Shot 2019-06-28 at 11 22 33 AM](https://user-images.githubusercontent.com/1753893/60353093-45b34a00-9997-11e9-8926-ea275aa4ae5c.png)

Example: 
https://www.wormbase.org/species/c_elegans/protein/CE18723#06--10

**Comment by chris-grove** [comment] 2019-06-28 15:40
Hi @sibyl229 
This is a duplicate of #7133 and #7125

**Closed by chris-grove** 2019-06-28 15:40 UTC
