### ISSUE TITLE
Genetic Map Viewer errors

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4472] opened 2016-01-07 23:22 UTC
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

Chris: Hi Sarah, how can I help?</br>visitor_name (visitor_email): the genetic map doesn't seem to be working today - on any of the browsers i've tried.</br>visitor_name (visitor_email): if i try to specify a value it gives a broken image.</br>Chris: OK, apologies, let me take a look</br>visitor_name (visitor_email): thanks!</br>Chris: Yes, I see the problem you're getting</br>Chris: I'll post a ticket in our issue tracker right away; hopefully out web team can get a fix soon</br>Chris: It seems that sometimes it works and sometimes it doesn't</br>Chris: have you noticed any pattern to what works and what doesn't? Any details will help us solve the problem</br>visitor_name (visitor_email): not really. it was working wonderfully yesterday for several of the regions I'm looking at.</br>visitor_name (visitor_email): and its not working at all today.</br>visitor_name (visitor_email): sorry i can't be more help. but thank you for looking into it</br>Chris: Sure, no problem. As soon as I have a handle on the problem or we have a fix, I will send you an e-mail, if that's OK</br>visitor_name (visitor_email): yes! thank you!</br>Chris: OK, great. Anything else I can help with?</br>visitor_name (visitor_email): nope. thats it. have a lovely day.</br>Chris: OK, thanks! You too!

**Reported by:** sara* (sea2**********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/tools/gmap/run">https://www.wormbase.org/tools/gmap/run</a>
**Browser:** Safari 9.0.2

**Comment by chris-grove** [comment] 2016-01-07 23:25
For me, this is only a problem on Firefox, for some reason. I can load all chromosomes except chromosome II which gives this error:
![screen shot 2016-01-07 at 3 24 06 pm](https://cloud.githubusercontent.com/assets/611382/12185871/c3a34dca-b552-11e5-9c5c-9e5f6af1057e.png)
I get the same loading error when trying to navigate any of the other chromosomes away from the default position of -0.18 to 0.18

**Comment by chris-grove** [comment] 2016-01-07 23:26
Email to Sarah:
"Hi again Sarah,

 I've tested out the issue, and for me it seems that only the Firefox
browser is having problems. In Firefox, loading chromosome II gives a
broken image icon and doesn't load for the default region (-.18 to .18),
but loading the other chromosomes works. Once I have any of the other
chromosomes loaded, however, any manipulation to the view (up, down,
shrink, or magnify) results in the same error and so is essentially
rendered useless.

 I cannot get this error to come up on Chrome or Safari.

You said you tried multiple web browsers and had the same problem?

Thanks!

Chris"

**Comment by chris-grove** [comment] 2016-01-07 23:32
​Hi, Chris. 

​I get the same error on all 3 browsers: chrome, firefox, and safari.

Just now I was using safari and loaded ChrX. I got the default region (-0.18 to 0.18) . But when I tried to switch to the region between 2.0 and 4.0 I got a broken image. 

Thanks,
Sarah

**Comment by chris-grove** [comment] 2016-01-07 23:43
OK, thanks for the info. Hopefully we can get a fix for this quickly. I
can send you an e-mail as soon as I know there's a fix in place.
Best,
 Chris

**Comment by chris-grove** [comment] 2016-01-07 23:43
Also, you can follow any progress on the issue on our GitHub ticket
tracker here:

https://github.com/WormBase/website/issues/4472

Chris

**Comment by chris-grove** [comment] 2016-01-07 23:43
Thanks, Chris!

I'll also add that searching for any rearrangement will also give the broken image -- but will result in the correct coordinates being "filled in" (and I sure that is not the right expression to use there, so I hope you understand what I'm trying to say).  

-Sarah

**Comment by chris-grove** [comment] 2016-01-07 23:46
I see. OK, thanks for letting me know. I cannot seem to replicate the rearrangement error. Just to check, can you send me a couple rearrangements that you've tried and aren't working?

Chris

**Comment by chris-grove** [comment] 2016-01-08 00:23
From Sarah:
![screen shot 2016-01-07 at 6 47 24 pm](https://cloud.githubusercontent.com/assets/611382/12186805/04e40204-b55b-11e5-81a0-f7b4154c8065.png)
![screen shot 2016-01-07 at 6 48 30 pm](https://cloud.githubusercontent.com/assets/611382/12186807/0637a7c8-b55b-11e5-92be-e9ba5edb2c80.png)
![screen shot 2016-01-07 at 6 48 49 pm](https://cloud.githubusercontent.com/assets/611382/12186809/0804a754-b55b-11e5-9cd3-60e056dfc8a2.png)

**Comment by chris-grove** [comment] 2016-01-08 00:24
OK, thanks Sarah. I can't seem to reproduce the error with these (they
load correctly in all three browsers for me).

Hopefully that problem will also go away once we get the general bug fixed.

Thanks!

Chris

**Comment by chris-grove** [comment] 2016-01-08 17:58
Hello Sarah,

 The bugs that I was seeing with Firefox yesterday seem to have been resolved. Can you try again and let us know if you are still having trouble? Also, if it is still a problem, can you try performing a hard refresh on the Genetic Map Viewer page (hold SHIFT while cliking the browser's reload button). If that doesn't work maybe try clearing your browser's cache.

If that still doesn't solve your problem please let us know and we will see what else we can do.

Thanks,

Chris

**Comment by chris-grove** [comment] 2016-01-08 18:21
Seems to be working perfectly now (I'm currently using chrome). Thank you for all your help.
-S.

**Comment by chris-grove** [comment] 2016-01-08 18:21
OK great! I'm glad it's working for you again. You're welcome.

Best,
Chris

**Closed by chris-grove** 2016-01-08 18:21 UTC
Labels: bug, Bug Report, HelpDesk, source: online chat
