### ISSUE TITLE
Hi WormBase, I noticed in your expression pattern ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4697] opened 2016-03-28 16:11 UTC
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi WormBase, I noticed in your expression pattern page that the synopsis under the worm picture with the anatomical overlays, the text summary has an html tag &lt;br\&gt; in it.

**Reported by:** Shel********* (shel*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/all/expr_pattern/Expr7177#021--10">http://www.wormbase.org/species/all/expr_pattern/Expr7177#021--10</a>
**Browser:** Chrome 49.0.2623.87

**Comment by draciti** [comment] 2016-03-28 16:18
Hello Sheldon,
thank you for letting us know!
Best, 
Daniela

**Comment by draciti** [comment] 2016-03-28 16:22
Duplicate of #3899

**Closed by draciti** 2016-03-28 16:22 UTC
Labels: HelpDesk, source: offline chat
