### ISSUE TITLE
Problem with chromosome location

### ISSUE THREAD

**Issue by vanaukenk** [WormBase/website#5312] opened 2016-12-13 13:21 UTC
Hi,
I am trying to find the chromosomal location of a list of genes in wormine.
I uploaded the list, and all were identified. When I tried to add the colomn"start" from chromosome location I get:
"No Results

This query returns no results. You may wish to change its filters".

What am I doing wrong?

Thank you,

Yonatan

**Comment by vanaukenk** [comment] 2016-12-13 14:09
Hi Yonatan,


Thanks for writing to WormBase, and our apologies for the inconvenience with this query in WormMine. 


Our developers are currently working on a fix for this issue, but in the meantime you can use the WormBase Parasite BioMart tool to get the information you need.


From this page:


http://parasite.wormbase.org/biomart/martview


click on the Query Filters link on the left side of the page, click open the Gene options on the right hand list, tick the ID list limit box, and then enter your list of WB gene IDs, e.g. WBGene00000387, under the Gene stable ID(s) heading.


Then click on the Output Attributes link on the left side of the page, again open the Gene options list, and select Gene stable ID, Chromosome/scaffold name, the Gene start (bp) and Gene end (bp) attributes, and any other additional attributes you may wish to retrieve.


When you're done, click on Results and you should be returned a table listing all of the selected attributes.


If you have any additional questions or need further help, please let us know.


Best,

--Kimberly Van Auken

**Comment by chris-grove** [comment] 2016-12-13 18:35
This is a duplicate of #5160 
Closing.

**Closed by chris-grove** 2016-12-13 18:35 UTC
Labels: HelpDesk, Intermine
