### ISSUE TITLE
 Server Error: 500 at  rest/widget/variation/WBVar...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5041] opened 2016-08-18 07:31 UTC
*Submitted from the feedback form on the WormBase website.*

<p>Server Error: 500 at <a href="http://www.wormbase.org/rest/widget/variation/WBVar00146374/molecular_details">rest/widget/variation/WBVar00146374/molecular_details</a></p><p></p><p>Error Message:<br> Caught exception in WormBase::Web::Controller::REST->widget "Neither wild type sequence [CCGGTGGAAAACTAAACAGTCGTTTACACAACGATCCGCCTGAAAAGGCTTAGGACATTTATTTTGTTAGTAATAAAAAAATTTTAGCTAATTTTGCGATGGAGGACTCGGATTAAGCAGCACTTGCCGCATTTTGGGGACCTCGTGAAGTATGAACGAGTACGACTTTAATTTTTTTTTTAAAATGTACTTTTTAGACCTTTTATAGCTATTTTAGTTTCGCTTTTTTCAAACCCTCTGCTTAAATTTACGCAAGTCTAAAACTTATTTCCAATAAAGCGCGTTAATCGTCATCCCGCGCGAACGTAGGCAGACGCAGAGCGCAAAACGGTGTCAGAGAGCGTTAGTGCAATCTAGCGAAAAAGCCTAACCCTTCTTTATGTTAAGAAATTTCTGTTTTGTATAAATTTATAAATTTACCATTTTAACAAGTACTTTGAAGCAAAAAAAAAAGTTATTTCTTTTTTCCGCAGCATTCGCTTTTTGTCCCTTACGTTTTTTATCTCTGATGGCATGAGCGGCTCACGACATCGACGTTTAAAATCGAGCACAGTCCTGCGCT] nor reverse complment matches DNA [ggccaccttttgatttgtcagcaaatgtgttgctaggcggacttttccgaatcctgtaaataaaacaatcattatttttttaaaatcgattaaaacgctacctcctgagcctaattcgtcgtgaacggcgtaaaacccctggagcacttcatacttgctcatgctgaaattaaaaaaaaaattttacatgaaaaatctggaaaatatcgataaaatcaaagcgaaaaaagtttgggagacgaatttaaatgcgttcagattttgaataaaggttatttcgcgcaattagcagtagggcgcgcttgcatccgtctgcgtctcgcgttttgccacagtctctcgcaatcacgttagatcgctttttcggattgggaagaaatacaattctttaaagacaaaacatatttaaatatttaaatggtaaaattgttcatgaaacttcgttttttttttcaataaagaaaaaaggcgtcgtaagcgaaaaacagggaatgcaaaaaatagagactaccgtactcgccgagtgctgtagctgcaaattttagctcgtgtcaggacgcga] at /var/lib/jenkins/jobs/staging_build/workspace/lib/WormBase/API/Object/Variation.pm line 1729." </p>

**Reported by:** Nikh********* (nikh*****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36

**Comment by sibyl229** [comment] 2016-08-18 15:45
duplicate of #5042 .

**Closed** 2016-08-27 18:26 UTC
Labels: Bug Report, HelpDesk
