### ISSUE TITLE
  Hi folks - I'm having various errors ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4690] opened 2016-03-21 22:48 UTC
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi folks - I'm having various errors today while trying to do some simple queries.  Also I keep getting 504 Bad Gateway errors.  Maybe the two things are related?</p><p>What were you doing? <br />&nbsp;&nbsp;Simple WQL queries with HTML output.  "find strain "VC????" works as long as I don't get a Bad Gateway error, but then "follow variation" returns "No data found".  I was doing this last week and as I remember it worked fine.  The simple query "find variation" returns "No data found".</p>

**Reported by:** Mark******* (edgl**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; InfoPath.3; .NET4.0C; .NET4.0E; rv:11.0) like Gecko

**Comment by azurebrd** [comment] 2016-04-12 09:38
Duplicate of #4689

**Closed by azurebrd** 2016-04-12 09:38 UTC
Labels: Bug Report, HelpDesk
