### ISSUE TITLE
 Server Error: 500 at  rest/widget/gene/WBGene0000...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3805] opened 2015-04-21 18:08 UTC
<p>Server Error: 500 at <a href="http://www.wormbase.org/rest/widget/gene/WBGene00003774/sequences">rest/widget/gene/WBGene00003774/sequences</a></p><p></p><p>Error Message:<br> Caught exception in WormBase::Web::Controller::REST->widget "Can't call method "length" on an undefined value at /var/lib/jenkins/jobs/staging_build/workspace/lib/WormBase/API/Object/Gene.pm line 1695." </p><p>What were you doing? <br />&nbsp;&nbsp;reading the lusty argonian maid</p>

Reported by: efgr*********************  (obscured for privacy)
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36

**Comment by chris-grove** [comment] 2015-04-21 18:13
Looks like a duplicate of #3801

**Comment by tharris** [comment] 2015-04-24 05:49
This is resolved in WS248; I haven't yet had time to track down if this is a data or presentation issue, but resolution with a new release suggests the former.

**Comment by tharris** [comment] 2015-04-27 21:38
See #3801 for explanation.

**Closed** 2015-06-09 16:27 UTC
Labels: Bug Report, HelpDesk, Under testing
