### ISSUE TITLE
  Not everything! :-) But anatomy term ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6346] opened 2018-04-11 22:35 UTC
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Not everything! :-)<br/>But anatomy term searches o all types have bee dead at least 24 hours!!<br/>I love and need them.  Please fix!</p><p>What were you doing? <br />&nbsp;&nbsp;any anatomy search</p>

**Reported by:** Bill******* (mohl********************)
**Submitted from:** <a target="_blank" href="https://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36

**Comment by chris-grove** [comment] 2018-04-12 00:42
From Ranjana:
"I tried some anatomy term searches on WB, and they seem to be working now.  Could you elaborate a bit more on what you were trying to do.  Giving us the faulty URL or a screen shot may help us identify the problem.

(The anatomy terms from the Ontology browser tool are also working for me)"

**Comment by chris-grove** [comment] 2018-04-12 00:43
From user:
"
http://www.wormbase.org/db/get?name=URYDL;class=Anatomy_term

this sort of search works after an auto redirect in the browser window.  But no longer gives me a usable text string when accessed programmatically.  very recent change.  Was there just a new release?

Thanks!
"

**Comment by chris-grove** [comment] 2018-04-12 00:43
From user:
"
https://wormbase.org/species/all/anatomy_term/WBbt:0003993#012--9

above is the redirect based on initial url searched in chrome.

How can I generate from an actual cell name?
"

**Comment by chris-grove** [comment] 2018-04-12 00:44
From user:
"is there a straight cell-to-wbbt lookup query?"

**Comment by chris-grove** [comment] 2018-04-12 00:45
From @tharris 
"Quick note on the /get URI. 

That’s essentially what the /db/get script does: maps a cell name to a WBbt ID. That URL *always* redirects — it’s a generic resolver. If you want to skip the initial redirect, use https as the protocol. You’ll still end up redirected to the Anatomy term page for the cell. 

I believe there is a mapping file of cells to ids on the FTP site but I am on mobile at the moment and cannot easily check. "

**Comment by chris-grove** [comment] 2018-04-12 00:46
From me:
"Like Ranjana, I can't seem to reproduce the problem you are referring to. Are you trying to type in the name of a cell into the search box on the webpage? Or are you accessing anatomy pages programmatically?

There was a relatively recent change to the WormBase website that enforces https for security purposes that may be affecting your query. If you're trying to automatically generate URLs to the respective anatomy term pages and you need a mapping of anatomy term names to WBbt IDs, you can run the following query with WormMine:
 

<query name="" model="genomic" view="AnatomyTerm.name AnatomyTerm.primaryIdentifier" longDescription="" sortOrder="AnatomyTerm.name asc">
</query>

 
You can navigate to WormMine via the Tools menu:

http://intermine.wormbase.org/tools/wormmine/begin.do

and on the "QueryBuilder" tab click on "Import query from XML" paste in the above query XML, click "Submit", and then click on "Show results". You should be directed to a query results table listing each anatomy term and its corresponding ID. You can then export the results using the "Export" button.

Let us know if you're getting an error message somewhere. As Ranjana said, any specifics of exactly what you're doing when you encounter the problem and what the problem is will help us troubleshoot to solve your problem."

**Comment by chris-grove** [comment] 2018-04-12 13:37
https was the issue. User is happy. Closing.

**Closed by chris-grove** 2018-04-12 13:37 UTC
Labels: Everything's broken!, HelpDesk
