### ISSUE TITLE
Align EST end reads for cDNAs in JBrowse

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#5934] opened 2017-10-25 22:07 UTC
This could be an issue better dealt with on the sequence object curation end, but when viewing cDNAs in the "ESTs (best)" track in JBrowse, there are often cDNAs, especially for Yuji Kohara's yk clones, that have been artificially split into a 5' end read and a 3' end read and are displayed separately (and at different height levels) in JBrowse. This means that a user looking to see where a particular yk clone begins and ends with respect to a gene has to find the 5' read and the 3' read individually and then try to visually pair them up, which can be quite challenging. See for example the aqp-1 locus:

![screen shot 2017-10-25 at 5 59 25 pm](https://user-images.githubusercontent.com/611382/32025625-fe7e6c60-b9ae-11e7-80d1-43e759e5bf6a.png)

If someone is interested in seeing the extent of the yk clone yk1281f09, the need to find the glyph labeled "yk1281f09.5.1" near the top and the glyph labeled "yk1281f09.3.1" towards the bottom. In this case, and in many others presumably, these objects have extensive overlap, but it would be nice to see them lined up at the same level, or at least on subsequent levels, to be able to see the clone reads more easily.

**Comment by chris-grove** [comment] 2017-10-26 14:06
From @khowe 
"""
Without wishing to go all 1990's you, I should point out that Fmap displays grouping of 5' and 3' pairs natively, based on the data that is already in Acedb.

The GFF3 spec gives an example of how this information could be represented (and I say "could", because as ever, the spec is not prescriptive). See below. We do not currently represent our alignments in this way in our GFF3. But we could do that as a post-processing step.

Another direction that might be worth exploring is to put the alignments in BAM files, which can represent paired alignments elegantly (the EST pairs are very much analogous to Illumina paired-end reads).

ctg123 . cDNA_match 1200 9000 . . . ID=cDNA00001
ctg123 . match_part 1200 3200 2.2e-30 + . ID=match00002;Parent=cDNA00001;Target=mjm1123.5 5 506;Gap=M301 D1499 M201
ctg123 . match_part 7000 9000 7.4e-32 - . ID=match00003;Parent=cDNA00001;Target=mjm1123.3 1 502;Gap=M101 D1499 M401
"""

**Comment by scottcain** [comment] 2017-10-26 14:14
There are two routes we can go in implementing this: write a JBrowse plugin that implements the same "group by" behavior from GBrowse (not exactly sure how to do this, though I have at least a rough idea at the moment), or putting the ESTs in a BAM file, where the linking of forward and reverse reads is built in.  This has the additional advantage of taking the processing EST data with each release out of the pipeline (since I'm assuming the data in this track changes very infrequently, so the creating of the BAM file would be a one-off).  I don't care for the option of GFF3 hacks, which we could do, but I'm not sure that even if we did, there would be an easy display solution (that is, one without having to write an albeit simpler JBrowse plugin to deal with it and make it look good).

So, my preferred solution is the BAM file.  Are there downsides to this that I haven't considered?

**Comment by khowe** [comment] 2017-10-26 14:25
Although it's true that the Kohara EST set is static, we supplement it with new ESTs deposited in ENA/GenBank, pulled in as part of the preparation for each release. @Paul-Davis tells me that he cannot recall a single release when there wasn't at least a small additional set of ESTs added to the set. 

So, unfortunately, we would need to be producing new BAM files with each build, and replacing them in JBrowse each release. So not quite as convenient as a one-off task).

**Comment by scottcain** [comment] 2017-10-26 14:30
@khowe well darn, that makes it a little less attractive.  That may switch my preference to writing the JBrowse plugin, since it wouldn't require any changes in either the database build procedure at Hinxton or the browser build procedure at OICR.  I'll put a little time into researching the plugin route.

**Comment by scottcain** [comment] 2017-10-31 17:09
OK, just a little update on this.  The idea of not needing to modify the current GFF and just write a JBrowse plugin that will do the work is nice, but I fear it too will require a lot of work.  Basically the problem is that I need to write code that gets in between the data store and where the data are handed to the view generator to modify the data in situ.  It would be a lot easier to modify the GFF and then do fancy things with the newly created features.  As an example, I'm currently using this GFF that I created to work on developing a new glyph that will know how to do the dotted lines between the paired ESTs:

```
III     BLAT_EST_BEST   experimental_feature    7072753 7073843 .       .       .       ID=yk600e3
III     BLAT_EST_BEST   expressed_sequence_match        7072753 7073102 .       +       .       Parent=yk600e3;Name=yk600e3.3.1;_Clone=yk600e3.3;ID=yk600e3.3.1
III     BLAT_EST_BEST   match_part      7072753 7072968 99.3    +       .       Target=yk600e3.3 1 216 +;Parent=yk600e3.3.1
III     BLAT_EST_BEST   match_part      7073019 7073102 99.3    +       .       Target=yk600e3.3 217 300 +;Parent=yk600e3.3.1
III     BLAT_EST_BEST   expressed_sequence_match        7073261 7073843 .       -       .       Parent=yk600e3;Name=yk600e3.5.1;_Clone=yk600e3.5;ID=yk600e3.5.1
III     BLAT_EST_BEST   match_part      7073261 7073403 100     -       .       Target=yk600e3.5 218 360 +;Parent=yk600e3.5.1
III     BLAT_EST_BEST   match_part      7073581 7073714 100     -       .       Target=yk600e3.5 84 217 +;Parent=yk600e3.5.1
III     BLAT_EST_BEST   match_part      7073761 7073843 100     -       .       Target=yk600e3.5 1 83 +;Parent=yk600e3.5.1
```

What this rather annoying does though is add a new parent level feature (expreimental_feature) above all of the current expressed_sequence_match features regardless of whether they have a mate.  @khowe and @chris-grove  please feel free to express an opinion about this--I'm still early in the dev of what would be a new glyph to do this.

**Comment by chris-grove** [comment] 2017-10-31 18:49
@scottcain 
OK, I don't have much of an opinion about it at this point. What is the problem with generating a parent level feature? Another point I wanted to make is that often times yk clone end reads overlap considerably, meaning there wouldn't be any space for a dotted line connecting the two end reads on the same line in JBrowse. Maybe a way to display these is to control the order of the yk clones so that sister reads are on adjacent lines?

**Comment by khowe** [comment] 2017-10-31 19:42
@scottcain we can easily add these parent features to the GFF as part of the build - as soon as you've worked out exactly what you want it to look like. For example, given that many ESTs map to multiple places in the genome, should we just give all mappings the same clone parent, or only to "valid" pairs (i.e. alignments of a 5' and a 3' that are "close" together and in the correct orientation)?

**Comment by scottcain** [comment] 2017-10-31 20:00
@chris-grove since I'll be processing pairs as parts of the same thing, they would end up displaying by each other.  I probably will have to put in code to detect the overlap and them space them vertically (or not--it may just figure it out on it's own; that would be nice).

@khowe I'm not sure at the moment whether everything will need the new parent or just pairs.  I suspect I can write it in such a way that only the pairs will need it (and then I'll have to modify the loading code to load to catch both expressed_sequence_match and whatever the new parent is, and then write the glyph to look for both too.  It's a little bit of a hassle, and I have to consider what will happen with GBrowse too--I think and hope it will just ignore the new parents and continue to work as is, but it might require some modification too.  

Anyway, I won't know for sure what I want to do until I finish this new glyph any way (probably next week, since I'm going to the Genome Informatics meeting this week).

**Comment by scottcain** [comment] 2017-12-21 20:40
I don't have this completely solved for JBrowse yet, but I am making progess.  I have a new glyph that uses GFF modified from what we use at WB to give the paired ESTs a parent so they are grouped together (that is, the example from what I wrote on Oct 31).  Now the forward and reverse reads are grouped, but not yet on the same line and not linked by a dashed line, but this is progress.  The thing that is nice about even this minimal improvement is that when you mouse over them, they highlight together.  An example that could go away at any moment is here (note that this is the one and only EST pair in this track):

http://staging.wormbase.org/tools/genome/jbrowse-simple/full.html?data=data%2Fc_elegans_PRJNA13758&loc=III%3A7072544..7073855&tracks=test_est&highlight=

I'll also attach an image of what that looks like for when the above link does go away:
![highlighted est reads](https://user-images.githubusercontent.com/274751/34274109-2e36b614-e665-11e7-84fb-535b326e04b5.png)

**Comment by chris-grove** [comment] 2017-12-21 20:52
@scottcain  It's looking good!

**Comment by scottcain** [comment] 2017-12-22 19:05
More stuff I was thinking about (to fill my time while I puzzle about getting the dashed line between them) is whether we should color the ESTs differently if they don't have a mate, and coloring them differently for 3' and 5' ends, both of which are fairly common things in other tools.

**Comment by scottcain** [comment] 2017-12-28 15:35
@chris-grove and @khowe I experimented with postprocessing the EST GFF data and now have the following:

http://staging.wormbase.org/tools/genome/jbrowse-simple/full.html?data=data%2Fc_elegans_PRJNA13758&loc=II%3A13430250..13448499&tracks=Curated_Genes%2Ctest_est

Where the following are true:
*ESTs with with "near by" mates (within 100kb, a distance chosen at random) are light green.
*ESTs with mates that aren't nearby are dark green.
*ESTs with no mates are yellow.
*EST matches with mates that don't overlap appear on the same line horizontally and highlight together when moused over.  Overlapping 5' and 3' mates appear together but are staggered a little.

Here's a picture in case I break it before you check in after the new year:
<img width="542" alt="screen shot 2017-12-28 at 10 22 49 am" src="https://user-images.githubusercontent.com/274751/34414776-2325310c-ebb9-11e7-9b0a-f4fc8cb133d6.png">

Finally, the GFF looks like this:
```
V       BLAT_EST_BEST   experimental_feature    11888250        11888787        .       +       .       ID=yk1264a11-0;Name=yk1264a11;has_mate=2
III     BLAT_EST_BEST   experimental_feature    7572131 7572833 .       +       .       ID=yk1264a11-1;Name=yk1264a11;has_mate=2
V       BLAT_EST_BEST   expressed_sequence_match        11888250        11888787        .       +       .       ID=yk1264a11.5.1;Name=yk1264a11.5.1;Parent=yk1264a11-0;clone=yk1264a11.5;has_mate=2
V       BLAT_EST_BEST   match_part      11888250        11888577        98.6    +       .       Parent=yk1264a11.5.1;Target=yk1264a11.5 7 334 +
V       BLAT_EST_BEST   match_part      11888621        11888787        98.6    +       .       Parent=yk1264a11.5.1;Target=yk1264a11.5 335 501 +
III     BLAT_EST_BEST   expressed_sequence_match        7572131 7572833 .       +       .       ID=yk1264a11.3.2;Name=yk1264a11.3.2;Parent=yk1264a11-1;clone=yk1264a11.3;has_mate=2
III     BLAT_EST_BEST   match_part      7572131 7572150 89.7    +       .       Parent=yk1264a11.3.2;Target=yk1264a11.3 1 20 +
IV      BLAT_EST_BEST   experimental_feature    885346  890122  .       -       .       ID=yk514h9;Name=yk514h9;has_mate=1
IV      BLAT_EST_BEST   expressed_sequence_match        889825  890122  .       -       .       ID=yk514h9.3.1;Name=yk514h9.3.1;Parent=yk514h9;clone=yk514h9.3;has_mate=1
IV      BLAT_EST_BEST   match_part      889825  890092  98.7    -       .       Parent=yk514h9.3.1;Target=yk514h9.3 32 299 +
IV      BLAT_EST_BEST   match_part      890095  890122  98.7    -       .       Parent=yk514h9.3.1;Target=yk514h9.3 1 28 +
IV      BLAT_EST_BEST   expressed_sequence_match        885346  887414  .       +       .       ID=yk514h9.5.1;Name=yk514h9.5.1;Parent=yk514h9;clone=yk514h9.5;has_mate=1
IV      BLAT_EST_BEST   match_part      885346  885421  100     +       .       Parent=yk514h9.5.1;Target=yk514h9.5 1 76 +
IV      BLAT_EST_BEST   match_part      886442  886613  100     +       .       Parent=yk514h9.5.1;Target=yk514h9.5 77 248 +
IV      BLAT_EST_BEST   match_part      887289  887414  100     +       .       Parent=yk514h9.5.1;Target=yk514h9.5 249 374 +
I       BLAT_EST_BEST   experimental_feature    9762492 9763593 .       -       .       ID=EC004781;Name=EC004781;has_mate=0
I       BLAT_EST_BEST   expressed_sequence_match        9762492 9763593 .       -       .       ID=EC004781.1;Name=EC004781.1;Parent=EC004781;clone=EC004781;has_mate=0
I       BLAT_EST_BEST   match_part      9762492 9762651 99      -       .       Parent=EC004781.1;Target=EC004781 426 585 +
```

I don't think there is any need to modify how WormBase is creating our GFF; there are already several tracks for which I preprocess the data; adding this preprocessing won't really be much more additional work (it's a little more complicated processing that what I do for other tracks, but that doesn't matter).

**Comment by chris-grove** [comment] 2018-01-02 14:49
@scottcain 
It looks very nice!! I really like how you've paired up end reads. I also like the color code, although I'm concerned that it won't be clear to users what the colors represent. Will there be a clear indication of what the colors mean somewhere? A link to documentation or a pop-up window explaining it?

The dark green clones are interesting/important to note as they appear to be artifacts; randomly checking two (pairs) of these showed that each end resided on different chromosomes in each case. FWIW, the clone doesn't currently link to a live WB page, but I assume that's a detail to be worked out.
Thanks!

**Comment by scottcain** [comment] 2018-01-02 15:51
@chris-grove Thanks--I'm pretty happy with it too, though there are still tweaks I'm thinking about for it. Colors can be a pain, as they are rarely intuitive :-)  I could add a popup for the dark green ones indicating that the mate is somewhere else, and it's occurred to me that it would be nice to allow a user to easily navigate to the mate.  The problem with that is a standard left click is already doing something (or supposed to anyway).  I could make a mouseover pop up that says "Clone name. Note that this has a mate that resides elsewhere; right- or command- click on this feature to get a menu that includes a link to the other location." (Of course, then I have to provide the link in the right click menu.)

The left click links should be generating valid Clone urls, though I note at the moment the staging site is down.  If you click on the link at the top of the popup window and change the "staging" to "www" you should get a valid page.

Finally, I think I still would like to join the 5' and 3' reads with dashed lines.  While I like the "cleanness" of not having them and just showing the relationship with the grey mouseover highlight, that isn't conveyed unless you mouseover it.  If you want a screenshot or don't what to have to mouse over everything, that information should still be displayed.  I'm going to put off working on that until next week, when I'll be meeting with JBrowse developers in person.

**Comment by chris-grove** [comment] 2018-01-03 21:05
@scottcain 
OK, I don't think linking to the "mate" is a priority at the moment as long as people can link to the clone page from JBrowse. If we do color code, then I think it will be necessary to indicate what all of the colors mean, probably in a pop-up (or somewhere obvious).

Dashed lines would be nice.

**Comment by scottcain** [comment] 2018-02-06 19:03
Closed by this pull request: https://github.com/WormBase/website-genome-browsers/pull/33

Running live on staging for WS263.

**Closed by scottcain** 2018-02-06 19:03 UTC
Labels: feature request, jbrowse

**Comment by chris-grove** [comment] 2018-02-06 19:10
@scottcain 
It looks REALLY good! Thanks Scott!
