### ISSUE TITLE
 Server Error: 500 at  tools/blast_blat/run   
  E...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4560] opened 2016-02-07 00:14 UTC
*Submitted from the feedback form on the WormBase website.*

<p>Server Error: 500 at <a href="http://www.wormbase.org/tools/blast_blat/run">tools/blast_blat/run</a></p><p>
</p><p>Error Message:<br> Caught exception in WormBase::Web::Controller::Tools-&gt;tools "Illegal division by zero at /usr/local/wormbase/extlib/lib/perl5/Bio/Graphics/Panel.pm line 249, <gen12> line 1." </gen12></p>

**Reported by:** hich******************
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/blast_blat/run">/tools/blast_blat/run</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.103 Safari/537.36

**Comment by sibyl229** [comment] 2016-02-18 18:49
Duplicate of #4562. Closing.

**Closed by sibyl229** 2016-02-18 18:49 UTC
Labels: Bug Report, HelpDesk
