### ISSUE TITLE
 Server Error: 500 at  rest/widget/gene/WBGene0002...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3801] opened 2015-04-20 20:28 UTC
<p>Server Error: 500 at <a href="http://www.wormbase.org/rest/widget/gene/WBGene00022423/sequences">rest/widget/gene/WBGene00022423/sequences</a></p><p></p><p>Error Message:<br> Caught exception in WormBase::Web::Controller::REST->widget "Can't call method "length" on an undefined value at /var/lib/jenkins/jobs/staging_build/workspace/lib/WormBase/API/Object/Gene.pm line 1695." </p><p>What were you doing? <br />&nbsp;&nbsp;Loading the nhr-41 gene page</p>

Reported by: Kimb************** (vana****************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:37.0) Gecko/20100101 Firefox/37.0

**Comment by chris-grove** [comment] 2015-04-20 20:39
Confirmed on live site:
![screen shot 2015-04-20 at 1 38 44 pm](https://cloud.githubusercontent.com/assets/611382/7239980/ae2500a6-e762-11e4-85b4-0ae02b220590.png)

Works on staging

**Comment by chris-grove** [comment] 2015-04-20 20:41
@vanaukenk  Sorry, I didn't realize it was you who reported this ;)

**Comment by vanaukenk** [comment] 2015-04-20 20:51
No worries @chris-grove :-)

**Comment by tharris** [comment] 2015-04-24 05:49
This is resolved in WS248; I haven't yet had time to track down if this is a data or presentation issue.

**Comment by tharris** [comment] 2015-04-27 21:37
I believe all of these problems are due to missing CDS entries for some genes in the WS247 GFF.  Here's a diff between WS247 and WS248 for one of the affected genes, WBGene00001253.

```
[tharris@wb-dev: releases]> diff ~/248-F25C12.5.2 ~/247-F25C12.5.2 
2d1
< IV	WormBase	exon	1917854	1918117	.	+	.	Parent=Transcript:F52C12.5.2
3a3
> IV	WormBase	exon	1917854	1918117	.	+	.	Parent=Transcript:F52C12.5.2
18,24d17
< IV	WormBase	CDS	1917977	1918117	.	+	0	ID=CDS:F52C12.5;Parent=Transcript:F52C12.5.1,Transcript:F52C12.5.2;Name=F52C12.5;prediction_status=Confirmed;wormpep=WP:CE31536;locus=elt-6
< IV	WormBase	CDS	1918552	1918668	.	+	0	ID=CDS:F52C12.5;Parent=Transcript:F52C12.5.1,Transcript:F52C12.5.2
< IV	WormBase	CDS	1919172	1919388	.	+	0	ID=CDS:F52C12.5;Parent=Transcript:F52C12.5.1,Transcript:F52C12.5.2
< IV	WormBase	CDS	1919543	1919769	.	+	2	ID=CDS:F52C12.5;Parent=Transcript:F52C12.5.1,Transcript:F52C12.5.2
< IV	WormBase	CDS	1919833	1920021	.	+	0	ID=CDS:F52C12.5;Parent=Transcript:F52C12.5.1,Transcript:F52C12.5.2
< IV	WormBase	CDS	1921058	1921132	.	+	0	ID=CDS:F52C12.5;Parent=Transcript:F52C12.5.1,Transcript:F52C12.5.2
< IV	WormBase	CDS	1921205	1921342	.	+	0	ID=CDS:F52C12.5;Parent=Transcript:F52C12.5.1,Transcript:F52C12.5.2
```

We don't have an easy or direct way to fix this now unfortunately. This has been resolved in WS248.

**Closed** 2015-06-09 16:27 UTC
Labels: Bug Report, data (problem), HelpDesk, Under testing
