### ISSUE TITLE
  Tree view for http://www.wormbase.org...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5412] opened 2017-02-09 12:57 UTC
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Tree view for http://www.wormbase.org/species/c_elegans/variation/WBVar02144610 timed out and would not display.</p>

**Reported by:** Mich************* (mich*********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:51.0) Gecko/20100101 Firefox/51.0

**Comment by epaule** [comment] 2017-04-21 15:32
duplicate of #5436

**Closed by epaule** 2017-04-21 15:32 UTC
Labels: Bug Report, HelpDesk
