### ISSUE TITLE
Chris: Hello Andrea, how can I help? visitor_name ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5931] opened 2017-10-25 19:35 UTC
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

Chris: Hello Andrea, how can I help?</br>visitor_name (visitor_email): How can I see the available cDNAs?</br>visitor_name (visitor_email): specifically where they are located?</br>Chris: OK, sure</br>Chris: In the "Reagents" widget, you'll find a list of cDNAs</br>Chris: http://www.wormbase.org/species/c_elegans/gene/WBGene00000175#0-d-3</br>visitor_name (visitor_email): I can see the list, but want to see how complete they are. In the past I have been able to see them,</br>Chris: Click to expand the matching cDNAs</br>Chris: OK, there's two ways to see this:</br>Chris: 1) Look at the "Nucleotide Aligner" widget</br>Chris: http://www.wormbase.org/species/c_elegans/gene/WBGene00000175#0-j-3</br>Chris: which doesn't help you see which cDNAs are which</br>Chris: actually more than two ways, sorry</br>Chris: You can also click on the actual cDNA name in the "Matching cDNAs" list</br>Chris: to go to the cDNA page</br>Chris: http://www.wormbase.org/species/c_elegans/sequence/yk825e02.3#04--10</br>Chris: Here you can find the sequence end read, 5' or 3'</br>visitor_name (visitor_email): okay, great. Thanks!</br>Chris: You're welcome!</br>Chris: You can also look at the genome browser, like GBrowse</br>Chris: with an EST track turned on and with expanded labels</br>visitor_name (visitor_email): that sounds like what I have done in the past, just couldnt' remember</br>visitor_name (visitor_email): Again, thank you!</br>Chris: You're welcome! Is there anything else I can help you with?</br>visitor_name (visitor_email): That is all, thanks</br>Chris: OK, have a great day!</br>visitor_name (visitor_email): you too</br>Chris: Thanks!

**Reported by:** Andr************ (andr*************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00000175#04ic1-9gad3-3-4c">http://www.wormbase.org/species/c_elegans/gene/WBGene00000175#04ic1-9gad3-3-4c</a>
**Browser:** Chrome 61.0.3163.100

**Comment by chris-grove** [comment] 2017-10-25 19:53
Automatic duplicate of #5930

**Closed** 2017-10-25 19:53 UTC
Labels: HelpDesk, source: online chat
