### ISSUE TITLE
  How to buy C. elegans (M141)  What we...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5955] opened 2017-11-02 07:35 UTC
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;How to buy C. elegans (M141)</p><p>What were you doing? <br />&nbsp;&nbsp;To study the effect of spatial radiation on nematodes</p>

**Reported by:** meng*** (1884***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.104 Safari/537.36 Core/1.53.2345.400 QQBrowser/9.5.10533.400

**Comment by Paul-Davis** [comment] 2017-11-02 09:52
duplicate of #5957 #5956

**Closed by Paul-Davis** 2017-11-02 09:52 UTC
Labels: HelpDesk
