### ISSUE TITLE
  Hi,  I saw that T13F2.1a.1(transcript...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7116] opened 2019-05-13 03:32 UTC
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi, <br/>I saw that T13F2.1a.1(transcripted from fat-4 gene) have a bug.<br/>The spliced+UTR one show 5' UTR as Exon.<br/>Thank you for improving the WormBase.<br/>Sincerely,<br/>visitor_name</p>

**Reported by:** Prin*** (kkk1**************************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36

**Comment by chris-grove** [comment] 2019-05-13 13:21
Confirmed:

The new sequence display for this transcript: 

https://wormbase.org/species/c_elegans/transcript/T13F2.1a.1#06--10

appears to be erroneously color-coding the UTRs. Here' a Word Doc with the displayed spliced and unspliced sequences for the transcript:

https://www.dropbox.com/s/paw4h76a1hzpqyl/T13F2.1a.1_transcript_sequence_discrepancies_WS270.docx?dl=0

You can see that in the "Spliced + UTR" sequence, the 5'UTR and most of the 3'UTR are being displayed with yellow/orange highlighting and capital letters as if they are part of the coding exon. Compare with the unspliced sequences.

**Comment by sibyl229** [comment] 2019-05-13 15:31
@chris-grove Thanks for putting together the doc.

@a8wright looks like the features attribute of the `spliced` sequence is missing the 5' UTR and part of the 3' UTR. The 3' UTR for this transcript occurs on two exons with an intro taken out from the middle. I attached the screenshot below.
![Screen Shot 2019-05-13 at 11 24 18 AM](https://user-images.githubusercontent.com/1753893/57633816-250f6c00-7572-11e9-995d-913584f2adf3.png)

**Comment by sibyl229** [comment] 2019-05-13 17:16
@a8wright I fixed the 5' UTR problem for you 7ca2f871efb45f95b7683cdaa0e0544b16bb7a58, and made and deployed a new release. 

@chris-grove the 5' UTR of spliced sequence should be fixed on staging. It should be fixed on production within 24 hours when the cache expires. 

The 3' UTR issue where an UTR spans multiple exons is probably a rare situation? The fix is definitely more involved. I don't understand the code well enough to make this fix. @a8wright could you take a look when you are back?

**Comment by a8wright** [comment] 2019-05-13 17:22
Thanks for fixing this so quickly @Sibyl Gao <sibyl@wormbase.org>!

I am not how that would have happened. I haven't looked through the git
history but I must have accidentally deleted a single character at some
point.

Thanks again
Adam

**Comment by chris-grove** [comment] 2019-05-13 18:21
@sibyl229 
Thanks! I see the 5'UTR issue fixed in this case on staging. The 3'UTR issue is still there, as you mention. Cases where the 3'UTR spans multiple exons is actually not rare at all. This can happen for 5'UTRs as well. We would need to accommodate those situations.

**Comment by chris-grove** [comment] 2019-05-13 18:26
@sibyl229 
Just in case it would help to have examples, several transcripts for the gene in question, fat-4, and its neighboring gene, fat-3, have their respective 5'UTRs spanning many exons:

https://staging.wormbase.org/tools/genome/jbrowse-simple/?tracks=Curated_Genes&loc=IV%3A9797141..9807850&data=data%2Fc_elegans_PRJNA13758&highlight=

<img width="706" alt="Screenshot 2019-05-13 14 24 56" src="https://user-images.githubusercontent.com/611382/57644901-2305d700-758b-11e9-8ea9-dbeb3fff0142.png">
<img width="707" alt="Screenshot 2019-05-13 14 24 37" src="https://user-images.githubusercontent.com/611382/57644902-2305d700-758b-11e9-84eb-982f799d2be6.png">

**Comment by sibyl229** [comment] 2019-05-13 18:39
Thanks @chris-grove that's good to know, and thanks for the examples!

**Comment by Paul-Davis** [comment] 2019-05-14 11:32
As a side note: I've also had a look at the annotation and for the WS272 release, this final false 5bp exon will be removed.

**Comment by sibyl229** [comment] 2019-05-30 22:03
I think @a8wright has fixed the issue about multiple UTRs spanning exons. Closing.

**Closed by sibyl229** 2019-05-30 22:03 UTC
Labels: Bug Report, HelpDesk, Webteam
