### ISSUE TITLE
Chris: Hello Orna, how can I help? visitor_name (v...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6218] opened 2018-02-27 18:21 UTC
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

Chris: Hello Orna, how can I help?</br>visitor_name (visitor_email): Hi, I just noticed that the genes thta appear in a paper from my lab, Joseph-Strauss et al 2012 May 15;365(2):445-57. doi: 10.1016/j.ydbio.2012.02.036. are not curated in wormbase (I didn't check each one but the frist one I checked weren't there). It might be useful for readers interested in these proteins. Thanks, Orna</br>Chris: OK, thanks for the heads up. We'll take a look. Did you have specific curation requests, or just wanted to make sure that the paper was listed on those gene pages?</br>visitor_name (visitor_email): The latter. Thanks!</br>Chris: OK, we'll make sure they get connected. Thanks!</br>Chris: Is there anything else I can help you with?</br>visitor_name (visitor_email): nope, thanks.</br>Chris: OK, take care.</br>visitor_name (visitor_email): Hi again, another paper from my lab that isn't curated is Rahman et al Proc Natl Acad Sci U S A. 2014 Feb 18;111(7):2602-7. doi: 10.1073/pnas.1311635111. Epub 2014 Feb 3. (it's a good thing more recent papers are curated or I would have taken it personally...). thansk,</br>visitor_name (visitor_email): Thanks,</br>Chris: I'm going to make sure these genes are connected to the paper, FYI:</br>Chris: snr-1
snr-2
snr-4
snr-5
snr-6
snr-7
smn-1
F43G9.10
D1054.14
T10F2.4
prp-4
uaf-1
ran-3
rnp-6
npp-2
npp-1
npp-5
npp-9</br>Chris: You're welcome</br>visitor_name (visitor_email): thanks :)

**Reported by:** Orna********** (orna***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00004914#036-9ge-3">http://www.wormbase.org/species/c_elegans/gene/WBGene00004914#036-9ge-3</a>
**Browser:** Firefox 52.0

**Comment by chris-grove** [comment] 2018-02-27 18:21
Duplicate of #6217

**Closed by chris-grove** 2018-02-27 18:21 UTC
Labels: HelpDesk, source: online chat
