### ISSUE TITLE
  How can I get a file which have all d...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5315] opened 2016-12-14 03:08 UTC
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;How can I get a file which have all description of genes,include gene name,gene ID and it's functions.</p><p>What were you doing? <br />&nbsp;&nbsp; Get a file which have all description of genes,include gene name,gene ID and it's functions.</p>

**Reported by:** Li J****** (7477************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.89 Safari/537.36

**Comment by Paul-Davis** [comment] 2016-12-14 10:33
duplicate of #5316

**Closed by Paul-Davis** 2016-12-14 10:33 UTC
Labels: HelpDesk
