### ISSUE TITLE
Website display of regulatory interactions depicting a one-to-many interaction annotation as an all-to-all annotation

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#6790] opened 2018-12-13 21:48 UTC
@WBjae  and I just found that regulatory (other?) interactions are not quite displaying properly on the website. The problem happens when, for example, we have one regulator annotated simultaneously to many regulated genes in a single annotation. This is usually done because it saves a lot of time at the moment of curation to annotate to a bunch of regulated genes all in one go. The problem is that the website is displaying these as if the regulation interaction is occurring as all-to-all, where all possible pair-wise permutations are being listed, often times making a gene that is co-regulated with another gene appear as if it is actually the regulator ("effector") in the interactions display. One example is on the rho-1 gene page:

https://www.wormbase.org/species/c_elegans/gene/WBGene00004357#08--10

The first several interactions that show up in the table are all actually for a single interaction (WBInteraction000542793):

https://www.wormbase.org/species/all/interaction/WBInteraction000542793#0132--10

in which "Fucose-containing Polymer" is an other (non-gene) regulator of 32 other genes, including rho-1. The problem is that this single interaction is showing up on the rho-1 page is if rho-1 is the "effector"/regulator of the other 31 genes in the interaction. This is misleading and should be corrected. 

Another example is WBInteraction000536825:

https://www.wormbase.org/species/all/interaction/WBInteraction000536825#0132--10

in which a single regulator, pept-1, is shown to regulate several other regulated genes. On the hsp-110 page, for example, the problem is that many of these show up as if hsp-110 is the regulator ("effector") of all the other regulated genes in the interaction:

https://www.wormbase.org/species/c_elegans/gene/WBGene00016250#08--10

I think there are two, non-mutually exclusive solutions, that we can implement:

1) A fix in the web code to appropriately handle these interactions as one-to-many and not all-to-all. If this could be done reasonably quickly, it would be great as this can be quite confusing to users, and the other solution (below) would require waiting several releases before the curation end of it can be fixed

2) Fix the curation source such that these annotations have minimal participants like one-to-one relationships. This could slow down curation a bit, but we have ways to make it faster. This solution would require waiting until WS270 goes live in several months before the changes make it to the live site

**Comment by WBjae** [comment] 2018-12-14 00:10
Hi Sibyl and Chris,
This issue might happen to the "genetic interaction", too. But I'm not sure those are exactly same.
When I saw the genetic interaction of egl-3 (https://www.wormbase.org/species/c_elegans/gene/WBGene00001172#08--10), there was one multi-component genetic interaction (egl-3:egl-47:fipr-11, WBInteraction000500516). And then, I went to the Interaction OA to see actual annotation. Here I found the "effector gene" is egl-3 and the "affected variation" is tm828.
In this case, tm828 variation is located at the overlapped genes, egl-47 and fipr-11.
And, in the interaction table, egl-47 and fipr-11 are connected as a non-directional genetic interaction without any experimental data.
So, I don't know if this is caused by bug or "inferred" from something.

**Comment by WBjae** [comment] 2018-12-14 18:56
Thanks Chris for the history regarding complex curation. 
Now in the physical interaction there is only binary interaction type. So, current cyclic connection seems happening only in regulatory or genetic interaction.
Hi Sibyl, I think this should be somehow corrected urgently, since it has affected all the interaction table and cytoscape graph presentation.

**Comment by WBjae** [comment] 2018-12-14 20:34
@chris-grove 
Thanks for the comment.
What I'm saying physical Protein-protein interaction is binary now, as you may guess.
Yeas, I saw all those PGID you copied are protein-DNA.

**Comment by WBjae** [comment] 2018-12-14 20:58
@sibyl229 
You should read 'physical interaction' from my previous comment as 'physical protein-protein interaction'.
As Chris said, other physical interactions may be also displayed as cyclic connections.

**Comment by sibyl229** [comment] 2018-12-19 18:44
Hi @chris-grove and @WBjae there is a relatively simple fix I can do, but I'm not sure if it makes sense biologically. I'd like to hear your thoughts on this before implementing it.

The tentative solution is to only show an interaction if one of the _interactor pair_ is known to be an effector by this mapping (or another mapping or your choice):
```
  {:interactor-info.interactor-type/affected :affected
   :interactor-info.interactor-type/bait :affected
   :interactor-info.interactor-type/cis-regulated :affected
   :interactor-info.interactor-type/cis-regulator :effector
   :interactor-info.interactor-type/effector :effector
   :interactor-info.interactor-type/target :effector
   :interactor-info.interactor-type/trans-regulated :affected
   :interactor-info.interactor-type/trans-regulator :effector}
```

A potential problem I can see is that an interaction where none of its interactors are an effector won't get displayed, even if it's a binary interaction. Is that a problem?

**Comment by sibyl229** [comment] 2018-12-19 22:44
Thanks @WBjae . Do all the non-directional interactions have the Interactor_type set to non-directional? If so, I can modify the tentative solution to that the interactor pair has to:
- have at least one effector, OR
- both have Interactor_type set to non-directional

Does that make sense?

Essentially, I need a way to tell from the data when to treat the interactors as all-to-all and when to treat them as one-to-many. Do you know how to do that?

**Comment by WBjae** [comment] 2018-12-19 23:06
Thanks @sibyl229,

I think it sounds great to me, but we need to talk with Chris.
Currently, in my data type there is no one-to-many or many-to-one or many-to-many interaction.

**Comment by sibyl229** [comment] 2018-12-19 23:19
Yeah, let's talk with @chris-grove about this. I might ask him tomorrow morning. If he give me the "go ahead", I will implement the change. If it turns out more complicated, I will let you know. And maybe we can find some time to talk about this over.

**Comment by WBjae** [comment] 2018-12-19 23:44
@sibyl229 
All sounds great! Thanks Sibyl.

**Comment by WBjae** [comment] 2018-12-20 18:36
@sibyl229 
Thanks for all your hard work.
One question about this phrase.
:interactor-info.interactor-type/bait :affected

Is there any reason to put 'bait' as "affected"?

**Comment by sibyl229** [comment] 2018-12-21 16:31
Hi @WBjae @chris-grove that's a good question. I don't know. If bait and target need to be treated as non-directional, I can easily do that. Please let me know your decision on this. We can also revisit later, if you need time discussing this.

For now, staging has implemented the rules we discussed earlier, such that a pair has to either: 
- one of the pair has to an effector and the other one has to an affected, OR
- both of the pair have to be non-directional.

For testing: https://staging.wormbase.org/species/c_elegans/gene/WBGene00004357#8--3

**Comment by chris-grove** [comment] 2018-12-21 16:58
@WBjae 
The "bait"->"affected" mapping is arbitrary. It was decided to go with a generic column header for interactions of "Effector" and "Affected" and so force a mapping onto those terms. This should probably be replaced with "Interactor role" columns, but it adds more columns to the table.

@sibyl229 
Yes, the staging site page for rho-1 looks much better now! Thanks!

**Comment by sibyl229** [comment] 2018-12-21 17:32
@chris-grove no problem!

**Comment by WBjae** [comment] 2018-12-21 18:49
@sibyl229 
It's perfect! Thanks!
@chris-grove 
Thanks for the answer. Yes, I assumed that and now I understand it clearly. Thanks!

**Comment by sibyl229** [comment] 2018-12-23 01:17
@WBjae No problem! I'm closing this issue now, but please feel free to re-open it if you want to discuss anything.

**Closed by sibyl229** 2018-12-23 01:17 UTC
Labels: Webteam, bug
