### ISSUE TITLE
Chris: Hello Elia, how can I help? visitor_name (v...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5946] opened 2017-10-30 15:16 UTC
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

Chris: Hello Elia, how can I help?</br>visitor_name (visitor_email): Hi we found an error in this allele sequence</br>Chris: Ah OK</br>visitor_name (visitor_email): By sequencing the correct sequence of ar131 is attached</br>Chris: Can you please send the allele details to help@wormbase.org and we will make sure the appropriate curator addresses the problem.</br>visitor_name (visitor_email): ok</br>Chris: Thank you!!</br>Chris: Is there anything else I can help you with, or do you have any additional feedback?</br>visitor_name (visitor_email): no thanks</br>Chris: OK, have a nice day

**Reported by:** elia*********** (elia**********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/variation/WBVar00000213#026-45317-10">http://www.wormbase.org/species/c_elegans/variation/WBVar00000213#026-45317-10</a>
**Browser:** Chrome 61.0.3163.100

**Comment by chris-grove** [comment] 2017-10-30 15:18
Duplicate of #5945

**Closed by chris-grove** 2017-10-30 15:18 UTC
Labels: HelpDesk, source: online chat
