### ISSUE TITLE
  The WormMine site isn't working this ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4723] opened 2016-04-06 19:55 UTC
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;The WormMine site isn't working this week. I get a warning message: "Oops!http://im-dev.wormbase.org/tools/wormmine/service/ is incorrect" when I go to any of the WormMine pages.</p><p>What were you doing? <br />&nbsp;&nbsp;Trying to use WormMine.</p>

**Reported by:** Erik********* (erik**************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36

**Comment by chris-grove** [comment] 2016-04-06 23:37
Duplicate of #4717 . Closing

**Comment by chris-grove** [comment] 2016-04-06 23:38
Hi Erik, thanks for the heads up. We are aware of the issue with WormMine and are working to restore services as soon as possible. Is there some data that I can retrieve for you in the meantime?

Best,
Chris

**Closed by chris-grove** 2016-04-06 23:37 UTC
Labels: Everything's broken!, HelpDesk

**Comment by chris-grove** [comment] 2016-04-08 17:00
Hi Erik,

 WormMine is back up and running. Apologies for any inconvenience. Let us know if you have any more trouble.

Best,
Chris
