### ISSUE TITLE
Japonica JBrowse

### ISSUE THREAD

**Issue by epaule** [WormBase/website#6299] opened 2018-03-29 09:25 UTC
http://www.wormbase.org/tools/genome/jbrowse-simple/?loc=Contig16392%3A0..2160&data=data%2Fc_japonica_PRJNA12591

from http://www.wormbase.org/species/c_japonica/gene/WBGene00216785

doesn't show any tracks in contrast to GBrowse http://www.wormbase.org/tools/genome/gbrowse/c_japonica_PRJNA12591?name=Cjap.Contig16392:-331..2492

there should be a few exons of the C.japonica eat-4 gene fragment flying around there.

**Comment by scottcain** [comment] 2018-04-02 01:21
@a8wright and @sibyl229, I think this problem is probably related to the rest end point not giving the correct information for JBrowse when creating the JBrowse iframe.  When I take the location from GBrowse and paste it into JBrowse's search bar, and when I click on the "try the new genome browser" link, it goes to the right place, so it appears to just be a problem with the iframe generation, which is why I'm guessing the rest end point is doing the wrong thing (is that a reasonable guess--I'm still not terribly clear on the plumbing?).

**Comment by sibyl229** [comment] 2018-04-02 14:36
Hi @scottcain the link generation code is a bit different both on the API side and the template side. Just troubleshooting here:
The iframe currently has: `/tools/genome/jbrowse-simple/full.html?overview=0&loc=Contig16392%3A0..2160&data=data%2Fc_japonica_PRJNA12591&nav=0&tracklist=0`
and the "try new genome browser" link has: `/tools/genome/jbrowse-simple/?loc=Contig16392%3A0..2160&amp;data=data%2Fc_japonica_PRJNA12591`

Do you notice any problem with the links?

@a8wright Not sure what happened to your github reply above. You might want to make sure no sensitive info (like API key) is leaked.

**Comment by scottcain** [comment] 2018-04-02 14:43
Hmm, maybe this is a weird bug with JBrowse.  Those URLs look right.  Perhaps some sort of edge case that only happens in odd instances.  I'll keep poking it to see if I can turn anything up.

**Comment by sibyl229** [comment] 2018-04-02 15:31
@scottcain sounds good. Please let us know if something needs done on our side.

**Comment by scottcain** [comment] 2018-04-02 16:43
@sibyl229 and @a8wright : The URLs aren't right.  This is the problem: ```loc=Contig16392%3A0..2160``` .  The C. japonica contigs are named like ```Cjap.Contig16392```.  When JBrowse doesn't find one named Contig16392, it falls back to the first one alphabetically, which is Cjap.Contig0.  I'm not sure what to do about that or where the problem is.

**Comment by sibyl229** [comment] 2018-04-02 19:39
@scottcain the loc query parameter should be correct now. There was some faulty regex in the template code. Could you check if the one on staging now is working? https://staging.wormbase.org/species/c_japonica/gene/WBGene00216785#9--10 Thanks

**Comment by scottcain** [comment] 2018-04-02 19:49
Yes, it looks like it is getting it right (at first I thought it was getting the location right but which tracks to turn on wrong--but I think that was a caching issue--so easy to get bitten by that).

@epaule can you take a look too and verify that it looks right, and then close this issue if it is?

Thanks a lot @sibyl229 and @a8wright !

**Comment by sibyl229** [comment] 2018-04-02 19:54
Thanks @scottcain ! 

_Totall agree here that it's easy to get bitten by cache :)_

**Comment by epaule** [comment] 2018-04-03 08:49
* on the live side the link and iframe are still broken
* on staging, it looks good, except that the curated gene track should probably be turned on in the iframe

**Comment by scottcain** [comment] 2018-04-03 12:58
@epaule Can you try another browser or clear your cache--I experienced the same thing with the curated genes track not being turn on initially but trying another browser fixed it.

**Comment by epaule** [comment] 2018-04-03 13:08
after clearing the cache, it still behaves as above.
When I say "broken" I mean that the contig name is missing the prefix.

**Comment by scottcain** [comment] 2018-04-03 13:14
Sorry, I meant on staging--we know that production is still broken.

**Comment by epaule** [comment] 2018-04-03 13:18
staging still lacks the curated gene track in the iframe, else it is fine

**Comment by scottcain** [comment] 2018-04-03 13:33
@sibyl229 Maybe I was bit by some caching.  When I go to the page for that gene on staging on a fresh browser, the curate genes track isn't turned on.  The URL for the iframe is
```
/tools/genome/jbrowse-simple/full.html?overview=0&loc=Cjap.Contig16392%3A0..2160&data=data%2Fc_japonica_PRJNA12591&nav=0&tracklist=0
```

The iframe url is missing the "tracks" parameter like is present in other species pages, like ```tracks=Curated_Genes%2CClassical_alleles%2CYACs_Fosmids_Cosmids``` for elegans.  I think that has been hard coded in the past but can be obtained from the rest api now, right?

**Comment by sibyl229** [comment] 2018-04-03 14:48
Hi @scottcain @epaule sorry, that was my fault, the tracks parameter were only applied behind a conditional. That is fixed now: https://staging.wormbase.org/species/c_japonica/gene/WBGene00216785#9--10 Thanks!

**Closed** 2018-05-15 10:27 UTC
Labels: jbrowse
