### ISSUE TITLE
Duplicate InterPro2GO annotations?

### ISSUE THREAD

**Issue by vanaukenk** [WormBase/website#6766] opened 2018-12-03 20:10 UTC
Hi,

It looks like there may be duplicates of InterPro2GO-based IEA GO annotations on the live and staging sites.

Here are some examples:

https://wormbase.org/species/c_elegans/gene/WBGene00009595
MF annotations to 'transcription co-regulator activity', 'histone acetyltransferase activity', 'zinc ion binding'

https://staging.wormbase.org/species/c_briggsae/gene/WBGene00033987
MF annotations to 'nucleic acid binding'

For C. elegans, I double-checked the annotation file we upload just in case we had somehow failed to filter the InterPro2GO annotations we get from UniProt (which we routinely do), but they are not there.

**Comment by khowe** [comment] 2018-12-03 21:13
Hi @vanaukenk , 

These duplications are present in the WS267 Acedb database. It seems that script that adds the InterPro2GO was inadvertently run twice in quick succession. The duplicates are removed from the GAF during dump, but remain in display. 

The problem is fixed in WS268 Acedb - which staging.wormbase.org is supposed to be serving. I wonder therefore whether the underlying *Datomic* database is still on WS267 for staging. @a8wright @mgrbyte could you take a look at this?

If staging *is* being served by the correct WS268 Datomic database, then there may be a problem with the Acedb->Datomic conversion for WS268 (perhaps it used the WS267 Acedb db by mistake?)

**Comment by vanaukenk** [comment] 2018-12-03 21:20
Thanks for looking into this @khowe

**Comment by a8wright** [comment] 2018-12-04 00:46
Sibyl and I were out today. I will take a look tomorrow, consult with Sibyl
and let you know what we find.

**Comment by mgrbyte** [comment] 2018-12-04 10:35
Given the original example gene (WBGene00033987), there is only one associated term in the database, so looks to be a bug in the widget code.

**Comment by mgrbyte** [comment] 2018-12-04 12:49
@khowe You're right, at first glance it looked like this wasn't the case, but on further inspection:
The motif attached to the go annotation `00122204` has two "databases" attached, with distinct accessions (but looks to me like they should be the same thing) ?
```
:motif.database/accession "IPR013087"
:motif.database/accession "Znf_C2H2_type"
```
The data from the datomic entity api looks like this:
```
(#:motif.database{:database #:db{:id 7481077123135123},
                  :field #:db{:id 7362329961036358},
                  :accession "IPR013087"}
 #:motif.database{:database #:db{:id 7481077123135123},
                  :field #:db{:id 7362329960982399},
                  :accession "Znf_C2H2_type"})
```
the two distinct `:motif.database/field` entities are:
```
({:db/id 7362329961036358, :database-field/id "INTERPRO_ID"}
 {:db/id 7362329960982399, :database-field/id "short_name"})
```

**Comment by a8wright** [comment] 2018-12-04 16:09
@khowe I checked with @sibyl229 and staging was still running WS267. I have updated the d2c code "develop" branch to point to WS268. This is what should be currently running on staging. I have read over this thread and am not sure what the exact issue is. If there is still an issue let us know and we will look further into what is going on on our end.

**Closed** 2019-03-13 11:06 UTC
Labels: Hinxton, data (problem)
