### ISSUE TITLE
  Blast search for the wormbase is not ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6279] opened 2018-03-23 15:35 UTC
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Blast search for the wormbase is not working. If we start a search for nucleotide blast it shows that the "gateway timed out". Can you please help?</p>

**Reported by:** vkm2**************
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36

**Comment by chris-grove** [comment] 2018-03-23 16:51
Hello,


Apologies for the error. Are you still experiencing the problem with BLAST? It is working consistently for me right now.


Thanks for letting us know.


Chris Grove

WormBase

**Comment by chris-grove** [comment] 2018-03-23 17:01
Thanks for your email.
It's still not working.
It shows "504 Gateway Time-out" on nucleotide blast.

**Comment by chris-grove** [comment] 2018-03-23 18:25
Hmm.. very strange. I cannot reproduce the error on my computer.

Can you send me your exact BLAST query and search parameters? A screenshot will do.

Thanks,

Chris

**Comment by chris-grove** [comment] 2018-03-23 18:25
Here is the screen shot:

![blast_wormbase](https://user-images.githubusercontent.com/611382/37847107-0fe98a5e-2ea6-11e8-8eaa-83213a610fe5.png)

**Comment by chris-grove** [comment] 2018-03-23 18:26
OK thanks. I can reproduce your error now. For some reason BLAST is choking on the sequence input. I think I have the sequence right as:

CGCNTANACGACTCACTATAGGGCGAATTGGGTACCGGGCCCCCCCTCGAGG
TCGACGGTATCGATAAGCTTGATTGACAGTTTTAAGTGTTTCCGTCGTATA
AAAAAATCCCTCTAAATACTTCCGGGAAATTAATATCTGGCAAACGGCAAAT
TGGCGAACCGGCAAGTTGGCGGAATTGAAAATTTCCGGCAAATCGGCAAA
ACGGAAATTTGCCGATTTGCCTTTTTCAAGAAATAACACCGAATTTGAATAT
TTTCAAGTTTATTGCAGCGAACAATACTGTAATTTATGTATGTACAATAATTTA
ATTATTACATGTATTATTCAAAAAAATAGAGACAATGAAAAAAATAATTATTCA
GCAGATTTCTCTTCGACGATTGCCTGTTGAATTGGAATTGATCTTCCTTGAA
CCGCTTCTTTCTTTGGCGCTTCAATCGAAAGTTTACCATCTTCTGAAAGATTC
GAAGCAACTGCACCAACATCTACATCTTCAGGTAGAAGAATAACACGAGAA
AATGATTTTTTTGAATATCCATGATCAGTCTTCAATTCTTGTTCTCCTTGGATT
GATAGCGTACGACCATCCAAATTAATTTTCAAATCTTCTGGTTTAAACTGTGA
GACGTTGAGATTGATGGCAAACTTTTGATCATTGTTAACAATCTGAAAGCTG

Vinod, we will work on this issue. In the meantime, I am able to get BLAT to work with your sequence. Maybe that will suffice for the time being?

@tharris , do you have any ideas why BLAST would choke on this?

Chris

**Comment by chris-grove** [comment] 2018-03-23 18:43
This is the sequence..
CGCNTANACGACTCACTATAGGGCGAATTGGGTACCGGGCCCCCCCTCGAGGTCGACGGTATCGATAAGCTTGATTGACAGTTTTAAGTGTTTCCGTCGTATAAAAAAATCCCTCTAAATACTTCCGGGAAATTAATATCTGGCAAACGGCAAATTGGCGAACCGGCAAGTTGGCGGAATTGAAAATTTCCGGCAAATCGGCAAAACGGAAATTTGCCGATTTGCCTTTTTCAAGAAATAACACCGAATTTGAATATTTTCAAGTTTATTGCAGCGAACAATACTGTAATTTATGTATGTACAATAATTTAATTATTACATGTATTATTCAAAAAAATAGAGACAATGAAAAAAATAATTATTCAGCAGATTTCTCTTCGACGATTGCCTGTTGAATTGGAATTGATCTTCCTTGAACCGCTTCTTTCTTTGGCGCTTCAATCGAAAGTTTACCATCTTCTGAAAGATTCGAAGCAACTGCACCAACATCTACATCTTCAGGTAGAAGAATAACACGAGAAAATGATTTTTTTGAATATCCATGATCAGTCTTCAATTCTTGTTCTCCTTGGATTGATAGCGTACGACCATCCAAATTAATTTTCAAATCTTCTGGTTTAAACTGTGAGACGTTGAGATTGATGGCAAACTTTTGATCATTGTTAACAATCTGAAAGCTG

Ok. I think BLAT should be fine. What is the difference between the outputs for blast vs blat?
Thanks,

**Comment by chris-grove** [comment] 2018-03-23 18:43
BLAT performs a more efficient search for exact (or near exact) matches to the genome. If your searching for sequence that you know should be in the genome (or a very similar sequence) BLAT should suffice, in general, and will probably be faster. BLAST tends to look more deeply for more subtly aligned sequences (say a worm genomic sequence to a fly genomic sequence), tends to take longer and produce more results. In addition, the default BLAST search parameters include the "Filter" which "preprocesses the sequence to mask low-complexity regions", which may make the query even more complex and possibly take longer.

We'll keep looking into why there is an issue. At the very least, your query should return something more useful than a time-out error.

Thanks,

Chris

**Comment by chris-grove** [comment] 2018-03-23 19:54
Thanks for the information on BLAT. I have got the query 'blat'ed and looks like what we would expect.
Thanks for working on this.

**Comment by chris-grove** [comment] 2018-03-26 17:53
@WenChenWormBase 
This issue hasn't really been resolved, as the time-out is still occurring.

**Comment by tharris** [comment] 2018-03-26 18:04
If you remove searching the CB4856 Bioproject, the query completes. @sibyl229 Can you make it so that only the primary C. elegans Bioproject is autoselected?  There really isn't a reason to be searching both by default.

**Comment by sibyl229** [comment] 2018-04-27 00:35
Hi @Paul-Davis The problem with Blast should be fixed on staging now using the approach Todd described. Could you try it again? Thanks!

**Comment by chris-grove** [comment] 2018-04-27 13:51
@sibyl229 
OK, yes, BLASTing the sequence now works on staging. I'll close the ticket.

**Closed by chris-grove** 2018-04-27 13:51 UTC
Labels: Bug Report, HelpDesk, Helped, Under testing, Webteam
