### ISSUE TITLE
Hi 

slight glitch on searching for che-13 in "gen...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4912] opened 2016-06-20 13:34 UTC
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi 

slight glitch on searching for che-13 in "gene", links to the drosophila gene page rather then the C. elegans one.  You can find the CE che-13 gene page if you search for che-13 in "all". Just a minor problem,

**Reported by:** Deli* (deli************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00000492#0123456789abcdefg--10">http://www.wormbase.org/species/c_elegans/gene/WBGene00000492#0123456789abcdefg--10</a>
**Browser:** Firefox 46.0

**Comment by epaule** [comment] 2016-06-20 13:44
that is kind of a duplicate of #4898 and would be probably solved if the autocomplete would show the species after the id.

**Comment by khowe** [comment] 2016-07-06 09:17
We did put a workaround in place in the build to cover for this: if the fly/zfish gene etc has the same public name as a worm gene, then put a species prefix in front of it. 

However, in this case, the fly gene is called "Che-13" (upper case "c"), so our code treated is as distinct from "che-13". Acedb, unfortunately, normalised both to "che-13" on storage. 

We will put in a fix for this in WS255.

**Comment by sibyl229** [comment] 2016-07-20 18:49
Hi @epaule I think the problem with searching for che-13 and alg-2 has been fixed. I have prevented search redirect on everything except ones associated with c_elegans and ones that aren't associated with any species (like GO, paper, etc). Do you think this works?

There is a related issue #4898 that can probably be closed, when this issue is ready.

Thanks!

**Comment by epaule** [comment] 2016-07-21 08:34
You fix works on the live site, but staging behaves in the old way.
Technically it solves the behaviour of the search, but personally I think it would be nice if the species would appear in the autocomplete so people can disambiguate themselves.

**Comment by sibyl229** [comment] 2016-07-26 20:57
Hi @epaule the autocomplete on staging now includes the species name in suggestion (if applicable) with @miyukimouse 's help. Autocompleting to entities not associated with a species (like GO term, person, etc) works just as before. Could you take a look please? Thank you!

**Comment by epaule** [comment] 2016-07-27 08:51
nice :-)

**Comment by sibyl229** [comment] 2016-07-27 14:55
@epaule Yay. Closing

**Closed by sibyl229** 2016-07-27 14:55 UTC
Labels: feature request, HelpDesk, Search, source: offline chat, Under testing, Webteam
