### ISSUE TITLE
Chris: Hello Cristina, how can I help? visitor_nam...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4744] opened 2016-04-12 20:46 UTC
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

Chris: Hello Cristina, how can I help?</br>visitor_name (visitor_email): Hello!  In the search box on the Wormbase home page, I can't seem to be able to search by "motif".  Is it possible to add this feature?</br>Chris: If you leave the search box blank and click on the magnifying glass search icon</br>Chris: You will be directed to a page where you can select additional data types, including motif</br>Chris: Because of the large number of types, the drop down list on the homepage is limited</br>Chris: but I agree it would be convenient to have it readily available</br>visitor_name (visitor_email): Thanks!  That's great!  Also, I was trying to find all genes that have a chromodomain and when I do that search I get genes that are not c.elegans-specific.  Is there a way for me to only retrieve c.elegans-specific genes?</br>Chris: How are you getting the list of genes exactly?</br>visitor_name (visitor_email): Sorry!  I think I got it!  I think this page that you directed me to is exactly what I was looking for!</br>Chris: OK, great!</br>Chris: Is there anything else I can help you with?</br>visitor_name (visitor_email): Oh, actually, I think I spoke too soon.  If I search for the chromodomain motif for all species from the page you directed me to, I get a list of proteins that have a chromodomain, but if I try to narrow it down by searching for c.elegans only, then I don't get any results.</br>Chris: OK</br>Chris: How are you trying to narrow down the search?</br>Chris: Oh, nevermind, I see what you mean</br>Chris: I think the problem here is that the motifs themselves are not species specific</br>Chris: Unfortunately, we can't narrow down the results to one species directly, but I will create a ticket to display the species of the resulting protein lists that you could then sort or filter on</br>visitor_name (visitor_email): That would be great!  Thank you so much!</br>Chris: Sure, you're welcome. In the meantime, I think sorting the list of protein names and scanning by eye for the protein names that don't start with a prefix for one of the other species should work</br>visitor_name (visitor_email): Yep, that's what i've been doing, but I just wasn't sure if I was missing something.  Thanks for all of your help!</br>Chris: You're welcome. Is there anything else I can help you with?</br>visitor_name (visitor_email): I think I'm all set!  Thanks, again, and have a great day!</br>Chris: OK, thanks. You too!

**Reported by:** Cris***************** (cagu*************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00002717#0d8c7-961-5">http://www.wormbase.org/species/c_elegans/gene/WBGene00002717#0d8c7-961-5</a>
**Browser:** Safari 8.0.2

**Comment by azurebrd** [comment] 2016-04-12 20:48
Duplicate of #4743

**Closed by azurebrd** 2016-04-12 20:48 UTC
Labels: HelpDesk, source: online chat
