### ISSUE TITLE
Can't access any of the links in the schema, for e...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4145] opened 2015-09-02 20:36 UTC
*Help Desk query collected when no chat operators were online. Follow up required.*

Can't access any of the links in the schema, for eg. 'Gene_info' or 'Molecular info' gives a 502, bad gateway error; this happens in many schema pages.
    
**Reported by:** Ranj*********** (ranj***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/tools/schema/run">http://www.wormbase.org/tools/schema/run</a>
**Browser:** Firefox 40.0

**Comment by tharris** [comment] 2015-09-02 21:02
Duplicate of #4143.

**Closed by tharris** 2015-09-02 21:02 UTC
Labels: HelpDesk, source: offline chat
