### ISSUE TITLE
  WormMine does not create list for me ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4995] opened 2016-07-26 21:14 UTC
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;WormMine does not create list for me to analyze.<br/>I have tried in Chrome, FireFox, and Edge browser. Once I enter a list, it stops at "Please wait" "Verifying identifier" and never move forward. <br/>I am also not able to log in using google account to access my saved list. </p>

**Reported by:** Kevi****** (pkke*****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36

**Comment by chris-grove** [comment] 2016-07-26 21:30
Hi Kevin,


 Thanks for reporting the problem and apologies for the inconvenience. Our team is aware of the issue and is working on a fix.


For now, from the WormMine homepage, click on "advanced" under the "Analyze a list" header, on the following page select a species in the "for Organism" drop down, and enter your list of genes. Click "Create List" to generate the list. Although it may take several minutes, this approach should work. Let us know if it does not.


Best,


Chris Grove

WormBase

**Comment by chris-grove** [comment] 2016-07-26 23:09
Hello Chris,

Thanks for the quick response. I was able to go through and see the list verified following your instruction, but after clicking save list, I was not able to see it ( [List>View] returns a error and said the problem is logged).

Please let me when this problem is solved if possible.

Thanks again for your help.
Kevin

**Comment by chris-grove** [comment] 2016-07-26 23:10
OK Kevin, sorry about that, and thanks for letting us know. We'll let you know as soon as we have a fix.


Chris

**Comment by chris-grove** [comment] 2016-08-01 18:25
@nuin @tharris  The list generation function seems to be fixed in WormMine. Is it a stable fix that I can report to Kevin? Or are you still working on it?

**Comment by chris-grove** [comment] 2016-08-09 17:25
Hello Christian,

Sorry about the long delay. It is working for me. I can upload a list and do analysis on the list.

Thanks for your help and info.

Kevin

**Closed by chris-grove** 2016-08-09 17:25 UTC
Labels: Bug Report, HelpDesk, Helped, Intermine
