### ISSUE TITLE
WS249 release notes

### ISSUE THREAD

**Issue by dasmoth** [WormBase/website#4141] opened 2015-09-01 07:34 UTC
The [release blog post](http://blog.wormbase.org/2015/08/31/new-release-of-wormbase-ws249/) looks kind-of sparse!  Probably not a problem in itself, but does place a bit more emphasis on the release notes on the main website.  [This](http://www.wormbase.org/about/wormbase_release_WS249#01--10) is what we're currently linking to.

- The page contains two widgets, both with title "Add new widget..."
- You have to scroll down several pages before getting to "News for this release".  Can't this go at the top?

**Comment by tharris** [comment] 2015-09-02 21:09
Whoever posted the release notes didn't name the widget or link to it correctly. Hinxton generates the build release notes. Maybe you can lean over and ask them to change the format.

**Comment by gw3** [comment] 2015-09-03 08:46
I've removed the text of the unwanted duplicate of the release notes, but this has still left an empty widget. I don't see how to delete a widget completely.

**Comment by tharris** [comment] 2015-11-13 06:23
Not our issue, but I'm assuming this is resolved. Fixed long ago.

**Closed by tharris** 2015-11-13 06:23 UTC
Labels: Hinxton
