### ISSUE TITLE
GO_annotation model updates

### ISSUE THREAD

**Issue by tharris** [WormBase/website#3662] opened 2015-03-05 22:00 UTC
Just wanted to pass along the new ?GO_annotation model for WS248 and also
a link to the GO display at PomBase that has some features I like for
displaying both a summary and a full view of the data.

The model is in WS248, but I pasted it below in the email as well.
The essence of the change is that we will no longer populate the ?GO_term
tag in the ?Gene model, but rather all GO data will be contained in
individual ?GO_annotation objects.  Each individual annotation corresponds
(roughly) to a single line of annotation in the GAF file that is on the WB
ftp site and that we submit to the GO Consortium.

?GO_annotation 	Gene ?Gene XREF GO_annotation
		GO_term ?GO_term XREF GO_annotation
		GO_code ?GO_code
               Annotation_relation NOT
                                   colocalizes_with
                                   contributes_to
                                   enables
                                   involved_in
                                   part_of
               Annotation_made_with Interacting_gene ?Gene
                                    Inferred_from_GO_term ?GO_term
                                    Motif ?Motif
                                    RNAi_result ?RNAi
                                    Variation ?Variation
                                    Phenotype ?Phenotype
                                    Database ?Database ?Database_field ?Text
               Annotation_extension Life_stage_relation ?Text UNIQUE
?Life_stage
                                    Gene_relation ?Text UNIQUE ?Gene
                                    Molecule_relation ?Text UNIQUE ?Molecule
                                    Anatomy_relation ?Text UNIQUE
?Anatomy_term
                                    GO_term_relation ?Text UNIQUE ?GO_term
               Annotation_isoform ?Text ?Protein
               Interacting_species ?Species ?Strain
               Reference ?Paper XREF GO_annotation
               GO_reference ?Database ?Database_field ?Text
               Contributed_by ?Analysis
	        Date_last_updated UNIQUE DateType

The gene pages at PomBase (cdc2 as an example: 
http://www.pombase.org/spombe/result/SPBC11B10.09) show a nice summary
overview, but then allow users to toggle to a full view and see more
details.  Users can also see details for individual annotations if they
only want that.  I particularly like that users can toggle between the
views without having to leave the main gene summary page.  For a lot of
MODs, you have to click to a new page to see the details of GO
annotations.

**Comment by vanaukenk** [comment] 2015-04-27 12:58
Hi,
Just a reminder that we will need a new GO display for WS248, since GO_annotations are now housed in a new class of that name.
To start, I think a simple table with columns corresponding to the tag names would be okay; we can refine from there.
Please let me know what additional info would be helpful from me.
Thanks,
--Kimberly

**Comment by sibyl229** [comment] 2015-05-04 16:25
Hi @vanaukenk Yes, I'm going to spend a lot time on this feature during WS248 development. A few question about Annotation_relation tag and Annotation_made_with tag: 
- I guess I'm suppose to take the verb from Annotation_relation tag and the nouns from Annotation_made_with, and put them into a phrase. Is that correct?
- Is it possible for an annotation to have multiple Annotation_relations or multiple Annotation_made_with?

Thank you Kimberly!

**Comment by vanaukenk** [comment] 2015-05-04 17:47
Hi @sibyl229,

Awesome; thanks so much.

I'll answer your second question first - it is possible for an annotation to have multiple Annotation_made_with entries as well as multiple Annotation_extension entries, but each GO_annotation should only have one Annotation_relation.  

The Annotation_relation tag holds the value for the relation between the gene and the GO term.  Right now, there are only three values for Annotation_relation: involved_in, enables, and part_of, for Biological Process, Molecular Function, and Cellular Component, respectively.  We could, in the GO display table, put each relation parenthetically underneath the main heading for the branch of the ontology, like this:

Biological Process
(involved in)

The reason that these values are associated with each annotation is that down the road we will need to dump them out into our GO annotation file, and also the number of these relations may increase as GO tries to become more expressive with their annotations.  This would mean that Biological Process could have more than one type of Annotation_relation, although each annotation would still only have one value.

For display of the Annotation_made_with and Annotation_extension tags, I was actually thinking of something fairly simple and adopting display features that are in use by SGD and PomBase.

For the Annotation_made_with entries, I like how SGD displays them.  In the column that displays the evidence code, they just add the term 'with' and follow that term with the entity entry in the Annotation_made_with tag (or the SGD equivalent of that tag):  
http://www.yeastgenome.org/locus/S000004219/overview  You'll need to click on the Gene Ontology Details link on the SGD page to see their table.

So, for example, this GO_annotation for hecd-1 in WS248:
GO_annotation : "00056641"
Gene    "WBGene00016405"
GO_term "GO:0031581"
GO_code "IGI"
Annotation_relation "involved_in"
Interacting_gene    "WBGene00006876"
Reference   "WBPaper00035946"
Contributed_by  "WormBase"
Date_last_updated   "2014-11-10"

Would be displayed something like this in WB:
hemidesmosome assembly    IGI with vab-10     

I would then place the Reference, Contributed_by, and Date_last_updated tag values in separate columns in the display table.

For annotation extensions, I like the way that PomBase displays them, underneath the GO term.  
http://www.pombase.org/spombe/result/SPAC1F5.04c

So for example, this GO_annotation for xbp-1 in WS248:
GO_annotation : "00000013"
Gene    "WBGene00006959"
GO_term "GO:0000977"
GO_code "IDA"
Annotation_relation "enables"
GO_term_relation    "happens_during"    "GO:0030968"
Gene_relation   "has_direct_input"  "WBGene00004804"
Reference   "WBPaper00044245"
Contributed_by  "WormBase"
Date_last_updated   "2013-11-13"

Would be displayed like this in WB:
RNA polymerase II regulatory region sequence-specific DNA binding
happens during: endoplasmic reticulum unfolded protein response
has direct input: skn-1

Again, the data for the GO_code, Reference, Contributed_by, and Date_last_updated tags would then go in separate columns in the display table.

Both of these displays group the essential information together which, I think, makes it easier to understand what those tag values refer to.

Please let me know if anything's unclear.  I'm happy to Skype any time, too, if that helps.

Looking forward to seeing the new data :-)

Many thanks,
--Kimberly

**Comment by sibyl229** [comment] 2015-05-07 14:55
Hi @vanaukenk I attached two screenshots. The first one kind of mimics the "full view" table found in PomBase, where each GO_annotation will occupy a single row, and the table is partitioned by GO_term with summary row for each partition. I'd like to hear your thought about this display vs the default version attached in the second screenshot. The code isn't quite ready for staging site yet, but I will show you a link to play with the display in a bit.
![screen shot 2015-05-06 at 6 19 51 pm](https://cloud.githubusercontent.com/assets/1753893/7517661/5724fa14-f4a4-11e4-91cb-6d935d05b377.png)
![screen shot 2015-05-06 at 6 23 27 pm](https://cloud.githubusercontent.com/assets/1753893/7518009/5e2db8e4-f4a6-11e4-9c08-55dee80c40ee.png)

**Comment by vanaukenk** [comment] 2015-05-07 15:05
Hi @sibyl229,

Thanks so much for the screenshots - I'm really excited to see what the new GO data looks like.
I much prefer the first screenshot without the 'redundant' lines of GO terms; I think it's much cleaner and easier to view.  What do you think?
My only suggestion on the first view would be to exchange the places of the With and Evidence code columns, so that Evidence code comes before the With column.

**Comment by dasmoth** [comment] 2015-05-07 15:08
The first of these looks nice -- definitely a worthwhile reduction in clutter.

In the longer term, I wonder if it's possible to collapse away more of the detail and start with a view which just emphasises the list of terms.  Along the lines of what Pombase is doing.

**Comment by vanaukenk** [comment] 2015-05-07 15:17
@dasmoth - definitely something to consider; I like the simplicity of the PomBase display.  
What details we hide vs collapse, though, may wind up being Evidence code-dependent, as it also is for PomBase.  @sibyl229 we can work on this.

**Comment by sibyl229** [comment] 2015-05-13 17:21
Thanks @vanaukenk @dasmoth for the suggestions! The new GO widget is on staging now: http://staging.wormbase.org/species/c_elegans/gene/WBGene00006959#0-3g-3

A question for @vanaukenk, do you know if there's any other class, besides Gene and GO_term that draws data from GO_annotation? A simple search gives me a bunch of classes that uses GO somehow, but I haven't checked them individually, whether they affected by the extraction of GO_annotation as a class. Here's a list of the classes (might be incomplete):
- motif
- homology group
- anatomy term
- expression pattern
- expression cluster
- picture
- process and pathway 

I still need to do a few things on GO_term page.

**Comment by vanaukenk** [comment] 2015-05-13 18:27
Hi @sibyl229  - Thanks again for the work on the GO_annotation display.  I'll look through some use cases carefully and let you know if I have any other thoughts/suggestions.

The only three classes that currently xref with GO_annotation are ?Gene, ?GO_term, and ?Paper.
The other classes refer to ?GO_term, but not to specific GO annotations, at least for now.

**Comment by vanaukenk** [comment] 2015-05-13 20:30
Hi @sibyl229,

Great job; nice to see all of this GO data on display.  I looked at two gene pages to start, one simple (rft-2) and one more complicated (pmk-1).  Here are a few suggestions; let me know what you think.

1) Would be nice to have the Annotation Extensions displayed underneath the GO term for the Summary view like it is for the Full view.  This keeps the display consistent and keeps conceptually related information together.

2) I have some long-term ideas about how to simplify the GO display for genes that have lots of annotations, but in the short-term could the default display be to sort the table rows alphabetically based on the first letter of the value in the Term tag of ?GO_term?  This isn't perfect, but does a reasonable job of keeping conceptually related terms together.  Note that for WS250, we are proposing to remove the Term tag and just use the Name tag in the ?GO_term model.  

3) There are a number of annotations with entries in the Annotation_made_with tags that refer to non-WB objects, so we will need to link out of WB to pages in SGD, UniProt, KEGG, etc.  The pmk-1 annotations have examples of these.  What's the preferred way of handling all of these URLs?  I can give you a list, but let me know what the standard SOP is.

4) For annotations that don't have an entry in the Reference tag, we will need to display what is in the GO_reference tag, which will also be a link out to a page at the GO's web site.

5) For the pmk-1 page, I didn't see the different colored rows in the tables for Molecular Function and Cellular Component, although they are there for Biological Process.

I am open to suggestions on what to do with terms that have many entries in the Annotation_made_with tags.  For pmk-1, this is illustrated by the annotations to GO:0006952, defense response.  There are many separate With entries based on one phenotype and many different RNAi experiments, plus one variation.  Although we need to have the full provenance of each annotation in the database, I can imagine that people would not find the list particularly helpful.  Perhaps for these types of annotations, we could list in the With column the WBPhenotype followed by the number of supporting RNAi experiments or variations.  Something like this:
pathogen susceptibility increased (18 RNAi, 1 variation)
We could then have an option to expand this column that would list the individual annotations.  I don't know how feasible this is, so let me know what you think.

Thanks again,
--Kimberly

**Comment by sibyl229** [comment] 2015-05-18 17:16
Hi @vanaukenk, 

1 - 2 ) easy to do. Will make the changes for this release.

3 - 4) I believe that if the schema is similar to GO_reference, the outlinking of the field should be easy enough. I need to check an example with GO_reference to be sure though.

5) Hmm, I think some other on the page crashed the javascript the table drawing library. I haven't been able to consistently reproduce it. But I think this can happen especially when certain elements takes too long to load. I suspect it's the expression widget. This might require quite some time to figure out what's going on. On the slightly positive side, production widget data is cached, so should load faster, and less likely to happen.

About the numerous RNAi in the annotated_with tag, I'd like to discuss with you after WS248 web code freeze, if that's okay? I don't think I will get it done before the freeze this Friday.

I updated the code for Association widget (GO_term) and Reference widget (Paper), could you let me know your thoughts on them? 
- http://staging.wormbase.org/species/all/go_term/GO:0040024#01--10 (GO_term)
- http://staging.wormbase.org/species/all/go_term/GO:0002119#01--10 (GO_term when there're too many annotations)
- http://staging.wormbase.org/resources/paper/WBPaper00005044#034--10 (Paper)

**Comment by vanaukenk** [comment] 2015-05-18 18:16
Hi @sibyl229 -- 
Thanks for the updates.  Here are a few more thoughts for WS248; we can discuss other things in more detail for the next release.

1) For the display on Paper pages, since what is shown is actually a GO term and links to the GO term page, let's change the Label on the display from GO annotations to GO terms.

2) For the table display on the GO_term pages, it would be nice, if possible, to also include the entries in the Annotation_made_with and Annotation_extension tags.  Otherwise, we wind up repeating information in the Details section multiple times without the key piece of information that distinguishes the different annotations.  In the example link you sent, scroll down to look at the daf-1 entry.  The last two IGI annotations have the same information in the details, but are distinguished by different entries in the Annotation_made_with fields.

3) In the Details section, it would be nice to list the Reference first, followed by the Date last updated, and Contributed by fields.  The Reference is really the most important piece of information in the Details.  It might even be nice to make the Reference entry bigger than the other two, if possible.

Let me know if you need clarification on anything.  We can talk about other details for future releases.
Thanks again for the new display - it's really nice to see!

--Kimberly

**Comment by sibyl229** [comment] 2015-05-19 16:10
Hi Kimberly,  thanks for your reply!

Could you describe how you'd like Annotation_made_with and
Annotation_extension tags shown on GO term page? In particular, I'm
interested in

- whether you want the content of the two tags to be injected into the
details toggle under the evidence code
- Or you'd something similar to the full view version of the Gene Ontology
tables on gene page?

Thank you!

**Comment by sibyl229** [comment] 2015-05-19 16:33
Hi Kimberly, another thought: can we list out all the extensions (coming
from multiple annotations objects) for a gene in **single** a table cell,
and in a separate column list out all the references? I also like to hear
your thoughts on what a user would care to see the most **in this table**.
As we have a lot of information, that may seem too much to be displayed in
one table.

Thank you!

**Comment by vanaukenk** [comment] 2015-05-19 17:48
Hi @sibyl229,

I think we can't actually list all annotation extensions in a single cell and then all references and all Annotation_made_with.  The reason for this is that we would then lose the correspondence of specific tags and values in a single annotation which is important for accurately capturing the supporting information for an annotation.  

As for what users would most like to see in the table, I think that what we have is actually pretty good.  The only two things I think might not be as critical for users are in the Details section and they are the Date and Contributed_by tag values.  However, for the latter, I think it's important to credit the groups who've done the work, so I'm a bit reluctant to remove that tag from the display.

A perhaps more promising avenue for simplifying the overall display would be to make use of the relations in the GO to show, by default, the more granular annotations.  We could then offer a link to a table that shows *all* GO annotations.

For example, if you look at the pmk-1 page:
http://staging.wormbase.org/species/c_elegans/gene/WBGene00004055

in the Molecular Function display, there are annotations to:

GO:0016740	transferase activity	
GO:0016772	transferase activity, transferring phosphorus-containing groups	
GO:0016301	kinase activity	
GO:0004672	protein kinase activity	
GO:0004674	protein serine/threonine kinase activity	 has direct input: skn-1
GO:0004707	MAP kinase activity	

These terms are all related to one another via is_a relations in the ontology, but it would probably be sufficient to only show the last two annotations, GO:0004674 and GO:0004707, in the summary view, and then include all annotations in a more detailed, or complete, table.  We would need to work out the exact rules for doing this, and I don't know how hard this would be to implement on the web site, but I do think it could help simplify the display for users. 

Let me know if anything's not clear, or if I've misunderstood something.  

Thanks,
--Kimberly

**Comment by sibyl229** [comment] 2015-05-19 19:09
Hi Kimberly,

Thanks for the detailed explanation. I can (after the WS248 web release) look into the hierarchy of GO_term to collapse away some GO_annoations. I guess they are more applicable to Gene page and Paper page?

I was meant to ask about the Associations widget on GO_term page, and what a user would expect to find there. As I’m not sure if and where to put the annotation_made_with and annotation_extension content in that table:
- whether the content of the two tags should be injected into the details toggle under the evidence code
- Or you'd something similar to the full view version of the Gene Ontology tables on gene page?

Sibyl

**Comment by vanaukenk** [comment] 2015-05-19 19:20
Thanks, Sibyl.

Yes, collapsing away some GO_annotations would be most applicable to the Gene and Paper pages, although in practice it would probably mostly affect the Gene pages since many of the higher level (less granular) terms come from automated mappings that don't reference a WBPaper.

For the Associations widget on the GO_term page, I would opt for a display similar to what is seen in the version of the Gene Ontology tables on the gene page.  Would a summary and full view toggle work on the GO_term page, as well? 
 I actually think we could get rid of the Description column; that's a lot of extra info and it would be nice to have a similar GO display on the Gene and GO_term pages.

--Kimberly

**Comment by sibyl229** [comment] 2015-05-20 22:14
Hi Kimberly, could you take a look at the GO_term association widget please? Here: http://staging.wormbase.org/species/all/go_term/GO:0006990#01--10 and http://sibyl.wormbase.org/species/all/go_term/GO:0002119#01--10

I haven't yet addressed some of the UI and naming issues you brought up. I will do that soon after. I'd like you to take a look at the association widget first, so I know whether I'm on the right track. Thanks!

**Comment by vanaukenk** [comment] 2015-05-21 14:09
Hi Sibyl,
I couldn't get to the siby.wormbase.org page (404 error), but what you have on staging looks okay to me, so you are definitely on the right track.

**Comment by sibyl229** [comment] 2015-05-21 14:31
Hi @vanaukenk oh sorry, I pasted the wrong url. Staging is the place I intended you to look at. 

Sounds good. Thanks! I will work on the other issues you have brought up, and will let you when I'm done.

**Comment by vanaukenk** [comment] 2015-06-01 21:41
Hi @sibyl229,
Was just reading through issue #3915 and I think we may have a similar issue wrt linking out for some of the entities in the With/From column of the GO_annotation data.
As an example, one of the link-outs is to UniProtKB keywords which have this URL structure:
http://www.uniprot.org/keywords/KW-0581
While another is to protein entities that have this URL structure:
http://www.uniprot.org/uniprot/Q03173

I can provide base URLs for the different links, if needed.  

Thx.
--Kimberly

**Comment by vanaukenk** [comment] 2015-07-08 16:17
Hi @sibyl229,

Following up on our conversation at Caltech, here is a list of URLs and sample GO_annotations for fixing the link outs in the With field of the GO widget.  At the end of the list, I've also included an example of a link out for a GO internal reference.  Let me know if you have any questions.
Thx.  Kimberly

HAMAP

Generic URL: http://hamap.expasy.org/unirule/MF_nnnnn

Sample URL: http://hamap.expasy.org/unirule/MF_03176

Sample GO_annotation:

GO_annotation : "00008956"
Gene    "WBGene00004028"
GO_term "GO:0005524"
GO_code "IEA"
Annotation_relation "enables"
Database    "HAMAP" "HAMAP_annotation_rule" "MF_03176"
GO_reference    "Gene Ontology Consortium"  "GO_REF"    "0000020"
Contributed_by  "UniProt_GOA"
Date_last_updated   "2015-06-27"



KEGG Enzyme IDs

Generic URL: http://www.genome.jp/dbget-bin/www_bget?ec:n.n.n.n

Sample URL: http://www.genome.jp/dbget-bin/www_bget?ec:2.7.7.7

Sample GO_annotation:

GO_annotation : "00000009"
Gene    "WBGene00020964"
GO_term "GO:0003887"
GO_code "IEA"
Annotation_relation "enables"
Database    "KEGG"  "KEGG_id"   "2.7.7.7"
GO_reference    "Gene Ontology Consortium"  "GO_REF"    "0000003"
Contributed_by  "UniProt_GOA"
Date_last_updated   "2015-04-04"



Panther Tree Node

Generic URL: http://pantree.org/node/annotationNode.jsp?id=PTNnnnnnnnnn

Sample URL: http://pantree.org/node/annotationNode.jsp?id=PTN000108561

Sample GO_annotation:

GO_annotation : "00000045"
Gene    "WBGene00006690"
GO_term "GO:0022841"
GO_code "IBA"
Annotation_relation "enables"
Database    "Panther"   "PanTree_node"  "PTN000108561"
GO_reference    "Gene Ontology Consortium"  "GO_REF"    "0000033"
Contributed_by  "GO_Central"
Date_last_updated   "2015-02-11"



UniPathway

Generic URL: http://www.grenoble.prabi.fr/obiwarehouse/unipathway/upa?upid=UPAnnnnn

Sample URL: http://www.grenoble.prabi.fr/obiwarehouse/unipathway/upa?upid=UPA00126

Sample GO_annotation:

GO_annotation : "00000108"
Gene    "WBGene00016583"
GO_term "GO:0009298"
GO_code "IEA"
Annotation_relation "involved_in"
Database    "UniPathway"    "Pathway_id"    "UPA00126"
GO_reference    "Gene Ontology Consortium"  "GO_REF"    "0000041"
Contributed_by  "UniProt_GOA"
Date_last_updated   "2015-04-04"


UniProtKB-Accessions

Generic URL: http://www.uniprot.org/uniprot/NNNNNN

Sample URL: http://www.uniprot.org/uniprot/P24014

Sample GO_annotation:

GO_annotation : "00009028"
Gene    "WBGene00004854"
GO_term "GO:0005102"
GO_code "ISS"
Annotation_relation "enables"
Database    "UniProt"   "UniProtAcc"    "P24014"
Reference   "WBPaper00004900"
Contributed_by  "WormBase"
Date_last_updated   "2010-02-16"



UniProtKB-KW (UniprotKB Keywords)

Generic URL:  http://www.uniprot.org/keywords/KW-nnnn

Sample URL:  http://www.uniprot.org/keywords/KW-0238

Sample GO_annotation:

GO_annotation : "00000002"
Gene    "WBGene00001435"
GO_term "GO:0003677"
GO_code "IEA"
Annotation_relation "enables"
Database    "UniProt"   "UniProtKB-KW"  "KW-0238"
GO_reference    "Gene Ontology Consortium"  "GO_REF"    "0000038"
Contributed_by  "UniProt_GOA"
Date_last_updated   "2015-04-04"



UniProtKB-SubCell

Generic URL: http://www.uniprot.org/locations/SL-nnnn

Sample URL: http://www.uniprot.org/locations/SL-0191

Sample GO_annotation:

GO_annotation : "00000021"
Gene    "WBGene00020964"
GO_term "GO:0005634"
GO_code "IEA"
Annotation_relation "part_of"
Database    "UniProt"   "UniProtKB-SubCell" "SL-0191"
GO_reference    "Gene Ontology Consortium"  "GO_REF"    "0000039"
Contributed_by  "UniProt_GOA"
Date_last_updated   "2015-04-04"




GO References

***Need to be displayed under details section***

Genetic URL: n/a

Sample URL: http://www.geneontology.org/cgi-bin/references.cgi

Sample GO_annotation:

GO_annotation : "00000005"
Gene    "WBGene00021535"
GO_term "GO:0008152"
GO_code "IEA"
Annotation_relation "involved_in"
Motif   "INTERPRO:IPR003439"
GO_reference    "Gene Ontology Consortium"  "GO_REF"    "0000002"
Contributed_by  "GOC"
Date_last_updated   "2015-04-04"

**Comment by vanaukenk** [comment] 2015-08-07 14:32
Hi Sibyl,

Just checking on the status of the link outs from the GO widget on the gene page.  There are a number of link outs in the With/From field, e.g. UniProt, Panther, KEGG, that don't lead to the correct external page, but instead result in linking to sometimes very long lists of matches to other WB objects.

See the full view on this gene page for examples:
http://staging.wormbase.org/species/c_elegans/gene/WBGene00002985

I've listed the correct URLs in an earlier post in this ticket, but please let me know if there's anything else I need to do.

Thanks,
--Kimberly

**Comment by sibyl229** [comment] 2015-08-07 22:55
Hi Kimberly,

The link out in GO widgets are almost done. It probably won't make to the
WS249 release though, due to caching. The cache for these widgets were
generated before the fix.

I will put the fix to staging for you to look at, once WS249 website is
live. Is that okay?

Thanks,

**Comment by vanaukenk** [comment] 2015-08-08 02:25
That sounds great; thanks very much Sibyl.
--Kimberly

**Comment by sibyl229** [comment] 2015-10-02 15:34
Hi @vanaukenk the external links in GO tables should be working now. http://staging.wormbase.org/species/c_elegans/gene/WBGene00009920#03-d-3 Could you please take a look? Thanks!

**Comment by vanaukenk** [comment] 2015-10-02 16:06
The external link outs are working great now; thanks so much @sibyl229!  Made my day :-).

**Closed by vanaukenk** 2015-10-02 16:06 UTC
Labels: !!! Resolve Now (this release)
